/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-10 20:38:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/uvind/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
    _jspx_dependants.put("file:/C:/Users/uvind/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1692435033110L));
    _jspx_dependants.put("jar:file:/C:/Users/uvind/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/fn.tld", Long.valueOf(1602854172000L));
    _jspx_dependants.put("file:/C:/Users/uvind/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244256642L));
    _jspx_dependants.put("jar:file:/C:/Users/uvind/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602854172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/cart.jsp(6,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/cart.jsp(7,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("contents");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(new jakarta.servlet.jsp.tagext.TagAdapter((jakarta.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/views/frontend/cart.jsp(52,44) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("myList");
      // /WEB-INF/views/frontend/cart.jsp(52,44) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/frontend/cart.jsp(52,44) 'camera(0),console(0),laptop(0)'",_jsp_getExpressionFactory().createValueExpression("camera(0),console(0),laptop(0)",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new jakarta.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(new jakarta.servlet.jsp.tagext.TagAdapter((jakarta.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/views/frontend/cart.jsp(55,44) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/frontend/cart.jsp(55,44) '${myList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${myList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/frontend/cart.jsp(55,44) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                                <div class=\"card shadow-0 border rounded-3 mt-3\">\r\n");
            out.write("                                                    <div class=\"card-body\">\r\n");
            out.write("                                                        <div class=\"row\">\r\n");
            out.write("                                                            <div class=\"col-6 col-lg-3 col-xl-3 mb-4 mb-lg-0\">\r\n");
            out.write("                                                                <div class=\"bg-image hover-zoom ripple rounded ripple-surface\">\r\n");
            out.write("                                                                    <img src=\"assets/images/products/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(".jpeg\" class=\"w-100\" />\r\n");
            out.write("                                                                    <a href=\"#!\">\r\n");
            out.write("                                                                        <div class=\"hover-overlay\">\r\n");
            out.write("                                                                            <div class=\"mask\" style=\"background-color: rgba(253, 253, 253, 0.15);\"></div>\r\n");
            out.write("                                                                        </div>\r\n");
            out.write("                                                                    </a>\r\n");
            out.write("                                                                </div>\r\n");
            out.write("                                                            </div>\r\n");
            out.write("                                                            <div class=\"col-6 col-lg-6 col-xl-6\">\r\n");
            out.write("                                                                <h5>Sony NEX-5R Compact 16.1mp Digital Camera Body Only Black</h5>\r\n");
            out.write("                                                                <div class=\"d-flex flex-row\">\r\n");
            out.write("                                                                    <div class=\"text-danger mb-1 me-2\">\r\n");
            out.write("                                                                        <i class=\"fa fa-star rated\"></i>\r\n");
            out.write("                                                                        <i class=\"fa fa-star rated\"></i>\r\n");
            out.write("                                                                        <i class=\"fa fa-star rated\"></i>\r\n");
            out.write("                                                                        <i class=\"fa fa-star\"></i>\r\n");
            out.write("                                                                        <i class=\"fa fa-star\"></i>\r\n");
            out.write("                                                                    </div>\r\n");
            out.write("                                                                </div>\r\n");
            out.write("                                                                <div class=\"mt-1 mb-0 text-muted small\">\r\n");
            out.write("                                                                    <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Error quo provident totam mollitia sequi incidunt debitis veniam, nostrum alias cumque doloremque ducimus rem odio reprehenderit porro dolorum facilis voluptatibus iste!</span>\r\n");
            out.write("                                                                </div>\r\n");
            out.write("                                                                <div class=\"border border-start-0 border-end-0 border-bottom-0 pt-2 border-top\">\r\n");
            out.write("                                                                    <div class=\"form-outline d-flex\">\r\n");
            out.write("                                                                        <label class=\"form-label me-3\" for=\"formControlReadonly\">Quantity</label>\r\n");
            out.write("                                                                        <span class=\"fs-5\"><a href=\"#\" class=\"link-dark\"><i class=\"bi bi-plus\"></i></a></span>\r\n");
            out.write("                                                                        <input class=\"form-control form-control-sm shadow-none\" style=\"width: 50px;\" id=\"formControlReadonly\" type=\"text\" placeholder=\"10\" aria-label=\"readonly input example\" readonly />\r\n");
            out.write("                                                                        <span class=\"fs-5\"><a href=\"#\" class=\"link-dark\"><i class=\"bi bi-dash\"></i></a></span>\r\n");
            out.write("                                                                    </div>\r\n");
            out.write("                                                                </div>\r\n");
            out.write("                                                            </div>\r\n");
            out.write("                                                            <div class=\"col-md-6 col-lg-3 col-xl-3 border-sm-start-none border-start\">\r\n");
            out.write("                                                                <div class=\"d-flex flex-row align-items-center mb-1\">\r\n");
            out.write("                                                                    <h4 class=\"mb-1 me-1\">Rs.100.00</h4>\r\n");
            out.write("                                                                    <span class=\"text-danger text-decoration-line-through\">Rs.20.00</span>\r\n");
            out.write("                                                                </div>\r\n");
            out.write("                                                                <h6 class=\"text-success\">Free shipping</h6>\r\n");
            out.write("                                                                <div class=\"d-flex flex-column mt-4\">\r\n");
            out.write("                                                                    <button class=\"btn shadow-none btn-primary product-btn btn-sm\" type=\"button\">Checkout</button>\r\n");
            out.write("                                                                    <button class=\"btn shadow-none product-outline btn-sm mt-2\" type=\"button\">\r\n");
            out.write("                                                                        Add to wishlist\r\n");
            out.write("                                                                    </button>\r\n");
            out.write("                                                                </div>\r\n");
            out.write("                                                            </div>\r\n");
            out.write("                                                        </div>\r\n");
            out.write("                                                    </div>\r\n");
            out.write("                                                </div>\r\n");
            out.write("                                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new jakarta.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\r');
      out.write('\n');
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <div class=\"container-fluid p-0\">\r\n");
      out.write("            <div class=\"row-fluid m-0\">\r\n");
      out.write("                <div class=\"col-12 text-center my-3\">\r\n");
      out.write("                    <!-- BreadCrumb -->\r\n");
      out.write("                    <div class=\"col-12 ps-4 mt-3\">\r\n");
      out.write("                        <nav style=\"--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);\" aria-label=\"breadcrumb\">\r\n");
      out.write("                            <ol class=\"breadcrumb mb-0\">\r\n");
      out.write("                                <li class=\"breadcrumb-item\"><a href=\"/newtech/\">Home</a></li>\r\n");
      out.write("                                <li class=\"breadcrumb-item active\" aria-current=\"page\">Product Cart</li>\r\n");
      out.write("                            </ol>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <span class=\"fw-bold fs-3\"><i class=\"fa-solid fa-cart-shopping\"></i> Product Cart</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"card\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <div class=\"row d-flex justify-content-center pb-5\">\r\n");
      out.write("                                <div class=\"col-md-8 col-xl-8 mb-4 mb-md-0\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <!-- Control Buttons -->\r\n");
      out.write("                                        <div class=\"col-12 px-0 mb-0 px-3\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-2 d-grid me-auto\">\r\n");
      out.write("                                                    <button type=\"button\" class=\"btn btn-sm text-nowrap\">\r\n");
      out.write("                                                        <a href=\"#\" class=\"icon-link icon-link-hover link-dark text-decoration-none\">\r\n");
      out.write("                                                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-arrow-left\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                                                <path fill-rule=\"evenodd\" d=\"M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z\" />\r\n");
      out.write("                                                            </svg>\r\n");
      out.write("                                                            <use xlink:href=\"#arrow-left\"></use>Continue Shopping\r\n");
      out.write("                                                        </a>\r\n");
      out.write("                                                    </button>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-lg-3 col-sm-4 col-6\">\r\n");
      out.write("                                                    <button type=\"button\" class=\" btn btn-outline-danger btn-sm\">Clear</button>\r\n");
      out.write("                                                    <button type=\"button\" class=\"btn btn-outline-success btn-sm\">Update Cart</button>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <!-- <div class=\"col-2 bg-danger\">\r\n");
      out.write("\r\n");
      out.write("                                                </div> -->\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-12\">\r\n");
      out.write("                                            <!-- cart cards start -->\r\n");
      out.write("                                            ");
      if (_jspx_meth_c_005fset_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("                                            <?php\r\n");
      out.write("\r\n");
      out.write("                                            <!-- cart card end -->\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <!-- Pagination -->\r\n");
      out.write("                                        <div class=\"col-12 d-flex justify-content-center mt-3\">\r\n");
      out.write("                                            <nav>\r\n");
      out.write("                                                <ul class=\"pagination\">\r\n");
      out.write("                                                    <li class=\"page-item\">\r\n");
      out.write("                                                        <a class=\"page-link\">Previous</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li class=\"page-item\"><a class=\"page-link shadow-none\" href=\"#\">1</a></li>\r\n");
      out.write("                                                    <li class=\"page-item pagination-active\" aria-current=\"page\">\r\n");
      out.write("                                                        <a class=\"page-link shadow-none\" href=\"#\">2</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li class=\"page-item shadow-none\"><a class=\"page-link shadow-none\" href=\"#\">3</a></li>\r\n");
      out.write("                                                    <li class=\"page-item\">\r\n");
      out.write("                                                        <a class=\"page-link shadow-none\" href=\"#\">Next</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </nav>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-4 col-xl-4 offset-xl-0\">\r\n");
      out.write("                                    <div class=\"row mx-0\">\r\n");
      out.write("                                        <!-- Total Price Summary Card -->\r\n");
      out.write("                                        <div class=\"col-12 px-0 mb-5\">\r\n");
      out.write("                                            <div class=\"rounded d-flex flex-column p-2 mt-3 shadow shadow-lg\" style=\"background-color: #f8f9fa;\">\r\n");
      out.write("                                                <div class=\"p-2 me-3\">\r\n");
      out.write("                                                    <h4>Summary of the Total Products</h4>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"p-2 d-flex\">\r\n");
      out.write("                                                    <div class=\"col-8\">Total Items <sub>(6)</sub></div>\r\n");
      out.write("                                                    <div class=\"ms-auto\">$186.76</div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"p-2 d-flex\">\r\n");
      out.write("                                                    <div class=\"col-8\">Shipping</div>\r\n");
      out.write("                                                    <div class=\"ms-auto\">$1000.00</div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"border-top px-2 mx-2\"></div>\r\n");
      out.write("                                                <div class=\"p-2 d-flex pt-3\">\r\n");
      out.write("                                                    <div class=\"col-8\"><b>Total</b></div>\r\n");
      out.write("                                                    <div class=\"ms-auto\"><b class=\"text-success\">$1186.00</b></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"p-2 d-flex pt-3 d-grid\">\r\n");
      out.write("                                                    <button class=\"btn btn-danger offset-1 col-10\"><a class=\"text-decoration-none link-light fw-bold\" href=\"checkout\">Proceed To Checkout</a></button>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <!-- information div -->\r\n");
      out.write("                                        <div class=\"col-12 px-0 order-0 order-md-1 mb-3\">\r\n");
      out.write("                                            <div class=\"row mx-0\">\r\n");
      out.write("                                                <!-- info -->\r\n");
      out.write("                                                <div class=\"col-12 px-0 border border-secondary\">\r\n");
      out.write("                                                    <div class=\"info-div-container scrollbar\">\r\n");
      out.write("                                                        <div class=\"info-div\">\r\n");
      out.write("                                                            <div class=\"row mx-0 px-2\">\r\n");
      out.write("                                                                <div class=\"col-3 col-sm-3 col-md-12 info-space px-1 text-sm-center text-md-start\">\r\n");
      out.write("                                                                    <div class=\"row py-3\">\r\n");
      out.write("                                                                        <div class=\"col-3 col-sm-12 col-md-3 text-center my-auto px-1 mb-sm-2 mb-md-0\">\r\n");
      out.write("                                                                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" fill=\"currentColor\" class=\"bi bi-file-earmark-text\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                                                                <path d=\"M5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zM5 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5z\" />\r\n");
      out.write("                                                                                <path d=\"M9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.5L9.5 0zm0 1v2A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5z\" />\r\n");
      out.write("                                                                            </svg>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-7 col-sm-12 col-md-9 my-auto px-0 px-sm-1 lh-sm info-desc\">\r\n");
      out.write("                                                                            <span>FREE DELIVERY</span><br>\r\n");
      out.write("                                                                            <span>On order over Rs.50.00</span>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-1 d-block d-sm-none\">\r\n");
      out.write("                                                                            <div class=\"vertical-line\"></div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"col-3 col-sm-3 col-md-12 info-space px-1 text-sm-center text-md-start\">\r\n");
      out.write("                                                                    <div class=\"row py-3\">\r\n");
      out.write("                                                                        <div class=\"col-3 col-sm-12 col-md-3 text-center my-auto px-1 mb-sm-2 mb-md-0\">\r\n");
      out.write("                                                                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" fill=\"currentColor\" class=\"bi bi-shield-shaded\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                                                                <path fill-rule=\"evenodd\" d=\"M8 14.933a.615.615 0 0 0 .1-.025c.076-.023.174-.061.294-.118.24-.113.547-.29.893-.533a10.726 10.726 0 0 0 2.287-2.233c1.527-1.997 2.807-5.031 2.253-9.188a.48.48 0 0 0-.328-.39c-.651-.213-1.75-.56-2.837-.855C9.552 1.29 8.531 1.067 8 1.067v13.866zM5.072.56C6.157.265 7.31 0 8 0s1.843.265 2.928.56c1.11.3 2.229.655 2.887.87a1.54 1.54 0 0 1 1.044 1.262c.596 4.477-.787 7.795-2.465 9.99a11.775 11.775 0 0 1-2.517 2.453 7.159 7.159 0 0 1-1.048.625c-.28.132-.581.24-.829.24s-.548-.108-.829-.24a7.158 7.158 0 0 1-1.048-.625 11.777 11.777 0 0 1-2.517-2.453C1.928 10.487.545 7.169 1.141 2.692A1.54 1.54 0 0 1 2.185 1.43 62.456 62.456 0 0 1 5.072.56z\" />\r\n");
      out.write("                                                                            </svg>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-7 col-sm-12 col-md-9 my-auto px-1 lh-sm info-desc\">\r\n");
      out.write("                                                                            <span>ORDER PROTECTION</span><br>\r\n");
      out.write("                                                                            <span>Encrypt Information</span>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-1 d-block d-sm-none\">\r\n");
      out.write("                                                                            <div class=\"vertical-line\"></div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"col-3 col-sm-3 col-md-12 info-space px-1 text-sm-center text-md-start\">\r\n");
      out.write("                                                                    <div class=\"row py-3\">\r\n");
      out.write("                                                                        <div class=\"col-3 col-sm-12 col-md-3 text-center my-auto px-1 mb-sm-2 mb-md-0\">\r\n");
      out.write("                                                                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" fill=\"currentColor\" class=\"bi bi-gift-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                                                                <path d=\"M3 2.5a2.5 2.5 0 0 1 5 0 2.5 2.5 0 0 1 5 0v.006c0 .07 0 .27-.038.494H15a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h2.038A2.968 2.968 0 0 1 3 2.506V2.5zm1.068.5H7v-.5a1.5 1.5 0 1 0-3 0c0 .085.002.274.045.43a.522.522 0 0 0 .023.07zM9 3h2.932a.56.56 0 0 0 .023-.07c.043-.156.045-.345.045-.43a1.5 1.5 0 0 0-3 0V3zm6 4v7.5a1.5 1.5 0 0 1-1.5 1.5H9V7h6zM2.5 16A1.5 1.5 0 0 1 1 14.5V7h6v9H2.5z\" />\r\n");
      out.write("                                                                            </svg>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-7 col-sm-12 col-md-9 my-auto px-1 lh-sm info-desc\">\r\n");
      out.write("                                                                            <span>PROMOTION GIFTS</span><br>\r\n");
      out.write("                                                                            <span>Special offers!</span>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-1 d-block d-sm-none\">\r\n");
      out.write("                                                                            <div class=\"vertical-line\"></div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"col-3 col-sm-3 col-md-12 px-1 text-sm-center text-md-start\">\r\n");
      out.write("                                                                    <div class=\"row py-3\">\r\n");
      out.write("                                                                        <div class=\"col-3 col-sm-12 col-md-3 text-center my-auto px-1 mb-sm-2 mb-md-0\">\r\n");
      out.write("                                                                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" fill=\"currentColor\" class=\"bi bi-cash-coin\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                                                                <path fill-rule=\"evenodd\" d=\"M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z\" />\r\n");
      out.write("                                                                                <path d=\"M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z\" />\r\n");
      out.write("                                                                                <path d=\"M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z\" />\r\n");
      out.write("                                                                                <path d=\"M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z\" />\r\n");
      out.write("                                                                            </svg>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-7 col-sm-12 col-md-9 my-auto px-1 lh-sm info-desc\">\r\n");
      out.write("                                                                            <span>MONEY BACK</span><br>\r\n");
      out.write("                                                                            <span>Return over 30 days</span>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
