/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-19 09:36:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class customerPartOfAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-12 customer-body d-none\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-12 pt-1 px-5\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-6 fs-4 text-light fw-semibold\">\r\n");
      out.write("                    <span>Customers</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-6 fs-6 fw-semibold mt-1\">\r\n");
      out.write("                    <nav style=\"--bs-breadcrumb-divider: '>';\" aria-label=\"breadcrumb\">\r\n");
      out.write("                        <ol class=\"breadcrumb text-secondary\">\r\n");
      out.write("                            <li class=\"breadcrumb-item  ms-auto\"><a href=\"#\" class=\"text-decoration-none\">Home</a></li>\r\n");
      out.write("                            <li class=\"breadcrumb-item text-secondary\" aria-current=\"page\">Customers</li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-12 px-4\">\r\n");
      out.write("            <div class=\"card bg-card-secondary-color my-0 py-0\" style=\"width: 100%;\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-12 col-md-3 mb-0 order-2 order-md-1\">\r\n");
      out.write("                                    <form class=\"d-flex\" role=\"search\">\r\n");
      out.write("                                        <div class=\"input-group input-group-sm\">\r\n");
      out.write("                                            <span class=\"input-group-text mx-0 pe-1 border-1 border-end-0 rounded-0 bg-transparent\" id=\"basic-addon1\"><i class=\"bi bi-search text-light\"></i></span>\r\n");
      out.write("                                            <input type=\"search\" class=\"form-control border-1 border-start-0 rounded-0 border-white bg-transparent text-light search-list\" style=\"box-shadow: none;\" placeholder=\"Search the Customers...\" aria-label=\"search\" aria-describedby=\"search\">\r\n");
      out.write("                                            <select class=\"form-select rounded-0\" style=\"box-shadow: none; max-width: max-content;\">\r\n");
      out.write("                                                <option selected>Filter</option>\r\n");
      out.write("                                                <option value=\"1\">Name</option>\r\n");
      out.write("                                                <option value=\"2\">Email</option>\r\n");
      out.write("                                                <option value=\"3\">Mobile</option>\r\n");
      out.write("                                            </select>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- This is large screen one diplay select section -->\r\n");
      out.write("                                <div class=\"col-12 col-md-auto flex-md-grow-1 flex-shrink-1 text-light order-3 order-md-2 d-none d-md-block\">\r\n");
      out.write("                                    <label class=\"\">Display </label>\r\n");
      out.write("                                    <div class=\"d-inline-block\">\r\n");
      out.write("                                        <select class=\"form-select form-select-sm ms-1 me-1\">\r\n");
      out.write("                                            <option value=\"10\">10</option>\r\n");
      out.write("                                            <option value=\"20\">20</option>\r\n");
      out.write("                                            <option value=\"-1\">All</option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <label>&nbsp;Customers</label>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-12 col-md-auto  order-1 order-md-3 text-center mb-3 mb-md-0\">\r\n");
      out.write("                                    <button class=\"btn export-btn icon-link-hover  rounded-0\">\r\n");
      out.write("                                        <i class=\"bi bi-file-earmark-arrow-down icon-link\"></i> Export\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                    <button class=\"btn btn-danger add-btn icon-link-hover rounded-0\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">\r\n");
      out.write("                                        <i class=\"bi bi-plus-circle-fill icon-link\"></i> Add Customer\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Add Customer Modal -->\r\n");
      out.write("                        <!-- Modal -->\r\n");
      out.write("                        <div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("                            <div class=\"modal-dialog  modal-dialog-centered\">\r\n");
      out.write("                                <div class=\"modal-content\">\r\n");
      out.write("                                    <div class=\"modal-header\">\r\n");
      out.write("                                        <h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Add Customer</h1>\r\n");
      out.write("                                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"modal-body\">\r\n");
      out.write("                                        <form class=\"row g-3\">\r\n");
      out.write("                                            <div class=\"col-md-6\">\r\n");
      out.write("                                                <label class=\"form-label\">Customer Name</label>\r\n");
      out.write("                                                <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-md-6\">\r\n");
      out.write("                                                <label for=\"inputPassword4\" class=\"form-label\">Password</label>\r\n");
      out.write("                                                <input type=\"password\" class=\"form-control\" id=\"inputPassword4\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-12\">\r\n");
      out.write("                                                <label for=\"inputAddress\" class=\"form-label\">Address</label>\r\n");
      out.write("                                                <input type=\"text\" class=\"form-control\" id=\"inputAddress\" placeholder=\"1234 Main St\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-12\">\r\n");
      out.write("                                                <label for=\"inputAddress2\" class=\"form-label\">Address 2</label>\r\n");
      out.write("                                                <input type=\"text\" class=\"form-control\" id=\"inputAddress2\" placeholder=\"Apartment, studio, or floor\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-md-6\">\r\n");
      out.write("                                                <label for=\"inputCity\" class=\"form-label\">City</label>\r\n");
      out.write("                                                <input type=\"text\" class=\"form-control\" id=\"inputCity\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-md-4\">\r\n");
      out.write("                                                <label for=\"inputState\" class=\"form-label\">State</label>\r\n");
      out.write("                                                <select id=\"inputState\" class=\"form-select\">\r\n");
      out.write("                                                    <option selected>Choose...</option>\r\n");
      out.write("                                                    <option>...</option>\r\n");
      out.write("                                                </select>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-md-2\">\r\n");
      out.write("                                                <label for=\"inputZip\" class=\"form-label\">Zip</label>\r\n");
      out.write("                                                <input type=\"text\" class=\"form-control\" id=\"inputZip\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"modal-footer\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("                                        <button type=\"button\" class=\"btn btn-primary\">Save changes</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Modal -->\r\n");
      out.write("                        <div class=\"col-12 px-2 mt-4 overflow-y-auto scrollbar\" style=\"height: 545px;\">\r\n");
      out.write("                            <table class=\"table table-dark table-striped table-hover table-responsive text-center text-nowrap\">\r\n");
      out.write("                                <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th><input class=\"form-check-input focus-ring\" type=\"checkbox\" id=\"checkboxNoLabel\" value=\"\"></th>\r\n");
      out.write("                                    <th class=\"position-relative\">Customer Name <a href=\"#\" class=\"stretched-link link-light icon-link text-decoration-none\" style=\"font-size: 10px;\"><i class=\"fa-solid fa-sort\"></i></a></th>\r\n");
      out.write("                                    <th class=\"position-relative\">Email <a href=\"#\" class=\"stretched-link link-light icon-link text-decoration-none\" style=\"font-size: 10px;\"><i class=\"fa-solid fa-sort\"></i></a></th>\r\n");
      out.write("                                    <th class=\"position-relative\">Phone <a href=\"#\" class=\"stretched-link link-light icon-link text-decoration-none\" style=\"font-size: 10px;\"><i class=\"fa-solid fa-sort\"></i></a></th>\r\n");
      out.write("                                    <th class=\"position-relative\">Location <a href=\"#\" class=\"stretched-link link-light icon-link text-decoration-none\" style=\"font-size: 10px;\"><i class=\"fa-solid fa-sort\"></i></a></th>\r\n");
      out.write("                                    <th class=\"position-relative\">Create Date <a href=\"#\" class=\"stretched-link link-light icon-link text-decoration-none\" style=\"font-size: 10px;\"><i class=\"fa-solid fa-sort\"></i></a></th>\r\n");
      out.write("                                    <th class=\"position-relative\">Status <a href=\"#\" class=\"stretched-link link-light icon-link text-decoration-none\" style=\"font-size: 10px;\"><i class=\"fa-solid fa-sort\"></i></a></th>\r\n");
      out.write("                                    <th class=\"position-relative\">Action <a href=\"#\" class=\"stretched-link link-light icon-link text-decoration-none\" style=\"font-size: 10px;\"><i class=\"fa-solid fa-sort\"></i></a></th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                </thead>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                <?php\r\n");
      out.write("                                                for ($i = 0; $i < 5; $i++) {\r\n");
      out.write("                                                ?>\r\n");
      out.write("                                <tr class=\"\">\r\n");
      out.write("                                    <td class=\"\">\r\n");
      out.write("                                        <input class=\"form-check-input focus-ring\" type=\"checkbox\" id=\"checkboxNoLabel\" value=\"\">\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"table-user\">\r\n");
      out.write("                                        <a href=\"#\" class=\"text-light text-decoration-none fw-semibold\">\r\n");
      out.write("                                            <img src=\"assets/images/userProfImgs/one.jpeg\" alt=\"table-user\" class=\"me-2 rounded-circle\" style=\"width: 2rem; height: 2rem;\">\r\n");
      out.write("                                            Rory Seekamp\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        078 5054 8877\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        roryamp@dayrep.com\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        United States\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"sorting_1\">\r\n");
      out.write("                                        03/24/2018\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <span class=\"badge blocked-state-badge text-danger\">Blocked</span>\r\n");
      out.write("                                    </td>\r\n");
      out.write("\r\n");
      out.write("                                    <td class=\"\">\r\n");
      out.write("                                        <a href=\"javascript:void(0);\" class=\"action-icon text-info mx-1 text-decoration-none\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Edit\">\r\n");
      out.write("                                            <i class=\"far fa-pen-to-square\"></i>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <a href=\"javascript:void(0);\" class=\"action-icon text-danger mx-1 text-decoration-none\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Block\">\r\n");
      out.write("                                            <i class=\"far fa-circle-xmark\"></i>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <a href=\"javascript:void(0);\" class=\"action-icon text-success mx-1 text-decoration-none\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Unblock\">\r\n");
      out.write("                                            <i class=\"far fa-circle-check\"></i>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </td>\r\n");
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"\">\r\n");
      out.write("                                    <td class=\"\">\r\n");
      out.write("                                        <input class=\"form-check-input focus-ring\" type=\"checkbox\" id=\"checkboxNoLabel\" value=\"\">\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"table-user\">\r\n");
      out.write("                                        <a href=\"#\" class=\"text-light text-decoration-none fw-semibold\">\r\n");
      out.write("                                            <img src=\"assets/images/userProfImgs/one.jpeg\" alt=\"table-user\" class=\"me-2 rounded-circle\" style=\"width: 2rem; height: 2rem;\">\r\n");
      out.write("                                            Rory Seekamp\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        078 5054 8877\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        roryamp@dayrep.com\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        United States\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"sorting_1\">\r\n");
      out.write("                                        03/24/2018\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <span class=\"badge active-state-badge text-success\">Active</span>\r\n");
      out.write("                                    </td>\r\n");
      out.write("\r\n");
      out.write("                                    <td class=\"\">\r\n");
      out.write("                                        <a href=\"javascript:void(0);\" class=\"action-icon text-info  mx-1 text-decoration-none\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Edit\">\r\n");
      out.write("                                            <i class=\"far fa-pen-to-square\"></i>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <a href=\"javascript:void(0);\" class=\"action-icon text-danger  mx-1 text-decoration-none\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Block\">\r\n");
      out.write("                                            <i class=\"far fa-circle-xmark\"></i>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <a href=\"javascript:void(0);\" class=\"action-icon text-success  mx-1 text-decoration-none\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Unblock\">\r\n");
      out.write("                                            <i class=\"far fa-circle-check\"></i>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </td>\r\n");
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <?php\r\n");
      out.write("                                                }\r\n");
      out.write("                                                ?>\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- This is small screen one diplay select section -->\r\n");
      out.write("                        <div class=\"col-6 text-light mt-3 d-block d-md-none\">\r\n");
      out.write("                            <label class=\"\">Display </label>\r\n");
      out.write("                            <div class=\"d-inline-block\">\r\n");
      out.write("                                <select class=\"form-select form-select-sm ms-md-1 me-md-1\">\r\n");
      out.write("                                    <option value=\"10\">10</option>\r\n");
      out.write("                                    <option value=\"20\">20</option>\r\n");
      out.write("                                    <option value=\"-1\">All</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <label class=\"\">&nbsp;Products</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-6 col-md-12 mt-2 mt-md-0\">\r\n");
      out.write("                            <div class=\"row align-items-center justify-content-between pe-0\">\r\n");
      out.write("                                <div class=\"col-auto d-flex\">\r\n");
      out.write("                                    <p class=\"mb-0 d-none d-sm-block me-3 fw-semi-bold text-900 text-light\" data-list-info=\"data-list-info\">Showing 1 to 10 <span class=\"text-600\"> of </span>15 Customers</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-auto d-flex\">\r\n");
      out.write("                                    <a href=\"#\" class=\" icon-link icon-link-hover link-light\" style=\"--bs-icon-link-transform: translate3d(-.300rem, 0, 0);\"><i class=\"bi bi-chevron-left\"></i></a>\r\n");
      out.write("                                    <ul class=\"mb-0 pagination\">\r\n");
      out.write("                                        <li class=\"active\"><button class=\"btn btn-primary text-light fw-semibold px-2 py-0 mx-1 mt-2 mb-0\" type=\"button\" data-i=\"1\" data-page=\"10\">1</button></li>\r\n");
      out.write("                                        <li><button class=\"btn text-light px-2 py-0  mt-2 mb-0\" type=\"button\" data-i=\"2\" data-page=\"10\">2</button></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <a href=\"#\" class=\" icon-link icon-link-hover text-light fw-semibold mx-1\"><i class=\"bi bi-chevron-right\"></i></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
