/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-19 09:33:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class dashboardPartOfAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-12 dashboard-body d-none\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-12 mt-2\">\r\n");
      out.write("            <h2 class=\"mb-2 text-light ms-md-3 text-center text-md-start\">Ecommerce Dashboard</h2>\r\n");
      out.write("            <h5 class=\"fw-semi-bold text-white-50 ms-md-3  text-center text-md-start\">Here’s what’s going on\r\n");
      out.write("                at your business right now\r\n");
      out.write("            </h5>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-12 mt-4\">\r\n");
      out.write("            <div class=\"row justify-content-md-around justify-content-between gy-2\">\r\n");
      out.write("                <div class=\"col-md-2 col-6  px-3 px-md-0\">\r\n");
      out.write("                    <div class=\"row admin-card text-light p-2\">\r\n");
      out.write("                        <div class=\"col-9\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-12 mt-2 admin-card-title\">CLIENTS</div>\r\n");
      out.write("                                <div class=\"col-12 fs-3\">6328</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-2 fs-2 mt-2\">\r\n");
      out.write("                            <i class=\"fa-solid fa-users\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 text-light\">\r\n");
      out.write("                            <div class=\"hr my-1 admin-card-hr\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-6\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"12 admin-card-subheading\">\r\n");
      out.write("                                            <span>TODAY CLIENTS</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-12 fs-5\">\r\n");
      out.write("                                            <span>57</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-6\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"12  admin-card-subheading\">\r\n");
      out.write("                                            <span>MONTHLY CLIENTS</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-12 fs-5\">\r\n");
      out.write("                                            <span>657</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-2 col-6 px-3 px-md-0\">\r\n");
      out.write("                    <div class=\"row admin-card text-light p-2\">\r\n");
      out.write("                        <div class=\"col-9\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-12 mt-2 admin-card-title\">ORDERS</div>\r\n");
      out.write("                                <div class=\"col-12 fs-3\">6328</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-2 fs-2 mt-2\">\r\n");
      out.write("                            <i class=\"bi bi-cart-fill\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 text-light\">\r\n");
      out.write("                            <div class=\"hr my-1 admin-card-hr\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-6\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"12  admin-card-subheading\">\r\n");
      out.write("                                            <span>TODAY ORDERS</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-12 fs-5\">\r\n");
      out.write("                                            <span>57</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-6\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"12  admin-card-subheading\">\r\n");
      out.write("                                            <span>MONTHLY ORDERS</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-12 fs-5\">\r\n");
      out.write("                                            <span>657</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-2 col-6  px-3 px-md-0\">\r\n");
      out.write("                    <div class=\"row admin-card text-light p-2\">\r\n");
      out.write("                        <div class=\"col-9\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-12 mt-2 admin-card-title\">RETURNS</div>\r\n");
      out.write("                                <div class=\"col-12 fs-3\">6328</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-2 fs-2 mt-2\">\r\n");
      out.write("                            <i class=\"fa-solid fa-rotate-left\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 text-light\">\r\n");
      out.write("                            <div class=\"hr my-1 admin-card-hr\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-6\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"12  admin-card-subheading\">\r\n");
      out.write("                                            <span>TODAY RETURNS</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-12 fs-5\">\r\n");
      out.write("                                            <span>57</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-6\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"12  admin-card-subheading\" style=\"font-size: 10px;\">\r\n");
      out.write("                                            <span>MONTHLY RETURNS</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-12 fs-5\">\r\n");
      out.write("                                            <span>657</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-2 col-6  px-3 px-md-0\">\r\n");
      out.write("                    <div class=\"row admin-card text-light p-2\">\r\n");
      out.write("                        <div class=\"col-9\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-12 mt-2 admin-card-title\">EARNINGS</div>\r\n");
      out.write("                                <div class=\"col-12 fs-3\">6328</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-2 fs-2 mt-2\">\r\n");
      out.write("                            <i class=\"fa-solid fa-chart-line\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 text-light\">\r\n");
      out.write("                            <div class=\"hr my-1 admin-card-hr\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-6\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"12  admin-card-subheading\">\r\n");
      out.write("                                            <span>TODAY EARNINGS</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-12 fs-5\">\r\n");
      out.write("                                            <span>57</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-6\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"12  admin-card-subheading\" style=\"font-size: 10px;\">\r\n");
      out.write("                                            <span>MONTHLY EARNING</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-12 fs-5\">\r\n");
      out.write("                                            <span>657</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-2 col-6  px-3 px-md-0\">\r\n");
      out.write("                    <div class=\"row admin-card text-light p-2\">\r\n");
      out.write("                        <div class=\"col-9\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-12 mt-2 admin-card-title\">PRODUCTS</div>\r\n");
      out.write("                                <div class=\"col-12 fs-3\">6328</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-2 fs-2 mt-2\">\r\n");
      out.write("                            <i class=\"fa-sharp fa-solid fa-boxes-stacked\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 text-light\">\r\n");
      out.write("                            <div class=\"hr my-1 admin-card-hr\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-6\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"12  admin-card-subheading\">\r\n");
      out.write("                                            <span>OUT STOCK</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-12 fs-5\">\r\n");
      out.write("                                            <span>57</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-6\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"12  admin-card-subheading\">\r\n");
      out.write("                                            <span>IN STOCK</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-12 fs-5\">\r\n");
      out.write("                                            <span>657</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-2 col-6  px-3 px-md-0 d-md-none\">\r\n");
      out.write("                    <div class=\"row admin-card text-light p-2\">\r\n");
      out.write("                        <div class=\"col-9\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-12 mt-2 admin-card-title\">EVENTS</div>\r\n");
      out.write("                                <div class=\"col-12 fs-3\">6328</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-2 fs-2 mt-2\">\r\n");
      out.write("                            <i class=\"fa-sharp fa-solid fa-boxes-stacked\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 text-light\">\r\n");
      out.write("                            <div class=\"hr my-1 admin-card-hr\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-6\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"12  admin-card-subheading\">\r\n");
      out.write("                                            <span>ON GOING</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-12 fs-5\">\r\n");
      out.write("                                            <span>57</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-6\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"12  admin-card-subheading\">\r\n");
      out.write("                                            <span>UP COMMING</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-12 fs-5\">\r\n");
      out.write("                                            <span>657</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-12 mt-3\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"card admin-card\">\r\n");
      out.write("                        <div class=\"d-flex card-header justify-content-between align-items-center\">\r\n");
      out.write("                            <h4 class=\"text-light\">Revenue</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body pt-0\">\r\n");
      out.write("                            <div class=\"chart-content-bg text-light\">\r\n");
      out.write("                                <div class=\"row text-center px-5 py-3 justify-content-md-center\">\r\n");
      out.write("                                    <div class=\"col-md-3 col-6 chart-secondary-content mx-md-2\">\r\n");
      out.write("                                        <p class=\"mb-0 mt-3\">Current Week</p>\r\n");
      out.write("                                        <h2 class=\"fw-normal mb-3\">\r\n");
      out.write("                                            <small class=\"mdi mdi-checkbox-blank-circle text-primary align-middle me-1\"></small>\r\n");
      out.write("                                            <span>$58,254</span>\r\n");
      out.write("                                        </h2>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-3 col-6 chart-secondary-content mx-md-2\">\r\n");
      out.write("                                        <p class=\"mb-0 mt-3\">Previous Week</p>\r\n");
      out.write("                                        <h2 class=\"fw-normal mb-3\">\r\n");
      out.write("                                            <small class=\"mdi mdi-checkbox-blank-circle text-success align-middle me-1\"></small>\r\n");
      out.write("                                            <span>$69,524</span>\r\n");
      out.write("                                        </h2>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"sales-chart\">\r\n");
      out.write("                                <div id=\"salesChart\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div> <!-- end card-body-->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6 col-12 mt-3\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"card admin-card\">\r\n");
      out.write("                        <div class=\"d-flex card-header justify-content-between align-items-center\">\r\n");
      out.write("                            <h4 class=\"text-light\">TOP 10 PRODUCTS</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body pt-0\">\r\n");
      out.write("                            <div class=\"product-chart\">\r\n");
      out.write("                                <div id=\"chart\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div> <!-- end card-body-->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-3 col-12 mt-3\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"card admin-card\">\r\n");
      out.write("                        <div class=\"card-header\">\r\n");
      out.write("                            <h4 class=\"text-light text-center\">WEEKLY SALES TARGET</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body pt-0\">\r\n");
      out.write("                            <div class=\"product-chart\">\r\n");
      out.write("                                <div id=\"progress\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-3 col-12 mt-3\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"card admin-card shadow\">\r\n");
      out.write("                        <div class=\"card-header text-light  text-center\">\r\n");
      out.write("                            <h4>PRODUCT CATEGORIES</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <div id=\"chart-donut\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-3 col-12 mt-3\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"card admin-card shadow\">\r\n");
      out.write("                        <div class=\"card-header text-light  text-center\">\r\n");
      out.write("                            <h4>SALES vs. PURCHASES</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <div id=\"chart-radar\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-3 col-12 mt-3\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"card admin-card\">\r\n");
      out.write("                        <div class=\"card-header\">\r\n");
      out.write("                            <h4 class=\"text-light text-center\">ACTIVE USERS</h4>\r\n");
      out.write("                            <div class=\"bg-secondary text-center text-dark fs-1 mt-4\">144</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body overflow-y-scroll\" style=\"height: 340px;\">\r\n");
      out.write("                            <table class=\"table table-borderless text-light\">\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>Active Pages</th>\r\n");
      out.write("                                    <th>Users</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <?php\r\n");
      out.write("                                            for ($i = 0; $i < 10; $i++) {\r\n");
      out.write("                                            ?>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>/products/brandix-z4</td>\r\n");
      out.write("                                    <td>15</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <?php\r\n");
      out.write("                                            }\r\n");
      out.write("                                            ?>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
