/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-10 18:05:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class invoice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/uvind/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
    _jspx_dependants.put("file:/C:/Users/uvind/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1692435033110L));
    _jspx_dependants.put("jar:file:/C:/Users/uvind/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/fn.tld", Long.valueOf(1602854172000L));
    _jspx_dependants.put("file:/C:/Users/uvind/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244256642L));
    _jspx_dependants.put("jar:file:/C:/Users/uvind/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602854172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/invoice.jsp(6,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/invoice.jsp(7,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("contents");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\r');
      out.write('\n');
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <div class=\"container-fluid p-0\">\r\n");
      out.write("            <div class=\"row-fluid m-0\">\r\n");
      out.write("                <!-- BreadCrumb -->\r\n");
      out.write("                <div class=\"col-12 ps-4 mt-3\">\r\n");
      out.write("                    <nav style=\"--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);\"\r\n");
      out.write("                         aria-label=\"breadcrumb\">\r\n");
      out.write("                        <ol class=\"breadcrumb\">\r\n");
      out.write("                            <li class=\"breadcrumb-item\"><a href=\"/newtech/\">Home</a></li>\r\n");
      out.write("                            <li class=\"breadcrumb-item\"><a href=\"productlistning\">Product Listning</a></li>\r\n");
      out.write("                            <li class=\"breadcrumb-item\"><a href=\"singleproductview\">single Product View</a></li>\r\n");
      out.write("                            <li class=\"breadcrumb-item active\" aria-current=\"page\">Advanced Search</li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-12 mt-3\">\r\n");
      out.write("                    <!--Saving Methods-->\r\n");
      out.write("                    <div class=\"col-12 btn-toolbar justify-content-end\">\r\n");
      out.write("                        <button class=\"btn btn-dark me-2\" onclick=\"printDiv();\"><i class=\"bi bi-printer-fill\">\r\n");
      out.write("                            Print </i></button>\r\n");
      out.write("                        <button class=\"btn btn-danger me-2\" id=\"generatePDF\"><i class=\"bi bi-file-earmark-pdf-fill\">\r\n");
      out.write("                            Save As PDF</i></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <hr class=\"\" style=\"border:1px solid #FF6D00 !important;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"GFG\">\r\n");
      out.write("                        <!--invoice header-->\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <!--img-->\r\n");
      out.write("                                <div class=\"col-6 ps-4\">\r\n");
      out.write("                                    <div class=\"invoiceheaderimg\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!--text-->\r\n");
      out.write("                                <div class=\"col-6\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-12 text-end fw-bold text-decoration-underline text-primary pe-4\">\r\n");
      out.write("                                            <div class=\"\">\r\n");
      out.write("                                                <img src=\"assets/images/logo/New Tech (5).png\" alt=\"logo\"\r\n");
      out.write("                                                     class=\"img-fluid\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-12 text-end fw-bold pe-5\">\r\n");
      out.write("                                            <span>No 104,<br/> Udahamullah,</br> Nugegoda</span><br/>\r\n");
      out.write("                                            <span>+94760391109</span><br/>\r\n");
      out.write("                                            <span>newTech@outlook.com</span><br/>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <hr class=\"\" style=\"border:1px solid #FF6D00 !important;\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--invoice body-->\r\n");
      out.write("                        <div class=\"col-12 mb-4\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-6 ps-4\">\r\n");
      out.write("                                    <h5>INVOICE TO :</h5>\r\n");
      out.write("                                    <h2>\r\n");
      out.write("                                        Rashmika Jayasooriya\r\n");
      out.write("                                    </h2>\r\n");
      out.write("                                    <span class=\"fw-bold\">74/20, Jaya Road,Udahamullah</span><br/>\r\n");
      out.write("                                    <span class=\"fw-bold text-decoration-underline\" style=\"color: #FF6D00;\">uvindurashmika20010405@outlook.com</span><br/>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-6 text-end mt-4 pe-4\">\r\n");
      out.write("                                    <h1>INVOICE 616b0d</h1>\r\n");
      out.write("                                    <span class=\"fw-bold\">Date of Invoice :</span>&nbsp;\r\n");
      out.write("                                    <span class=\"fw-bold\">2021-10-16</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--table-->\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"table-responsive mt-3 scrollbar\">\r\n");
      out.write("                                <table class=\"table table-striped table-hover table-light\">\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th scope=\"col\">#</th>\r\n");
      out.write("                                        <th scope=\"col\" class=\"text-nowrap\">Ordered Item Details</th>\r\n");
      out.write("                                        <th scope=\"col\">Purchased Date</th>\r\n");
      out.write("                                        <th scope=\"col\">Unit Price</th>\r\n");
      out.write("                                        <th scope=\"col\">Quantity</th>\r\n");
      out.write("                                        <th scope=\"col\">Products Total Price</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                    <?php\r\n");
      out.write("                                    for($i=0;$i<3;$i++){\r\n");
      out.write("                                        ?>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td scope=\"row\"><?php echo $i+1; ?></td>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <li>Product Name:- Sonoff Smart Home ZigBee Bridge Temperature Humidity\r\n");
      out.write("                                                    Motion Door Window Sensor\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>Product Description:- Lorem ipsum dolor sit amet.</li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        <td>2001/04/05</td>\r\n");
      out.write("                                        <td>Rs.2500.00</td>\r\n");
      out.write("                                        <td>2 units</td>\r\n");
      out.write("                                        <td>Rs.5500.00</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <?php\r\n");
      out.write("                                    }\r\n");
      out.write("                                    ?>\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                    <tfoot>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td colspan=\"3\" class=\"border-0\"></td>\r\n");
      out.write("                                        <td colspan=\"2\" class=\"fs-5 text-end\">SUBTOTAL</td>\r\n");
      out.write("                                        <td class=\"fs-5 text-end\">Rs.16500.00</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td colspan=\"3\" class=\"border-0\"></td>\r\n");
      out.write("                                        <td colspan=\"2\" class=\"fs-5 text-end \"\r\n");
      out.write("                                            style=\"border-color: #FF6D00 !important;\">Discount\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        <td class=\"fs-5 text-end\" style=\"border-color: #FF6D00 !important;\">Rs.1000.00\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td colspan=\"3\" class=\"border-0\"></td>\r\n");
      out.write("                                        <td colspan=\"2\" class=\"fs-5 text-end border-0 \"\r\n");
      out.write("                                            style=\"color: #FF6D00 !important;\">GRAND TOTAL\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        <td class=\"fs-5 text-end border-0 \" style=\"color: #FF6D00 !important;\">\r\n");
      out.write("                                            Rs.15500.00\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    </tfoot>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-4 ms-5\" style=\"margin-top:-100px; margin-bottom: 50px;\">\r\n");
      out.write("                                <span class=\"fs-1\">Thank You!</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--invoice notice -->\r\n");
      out.write("                        <div class=\"col-12 mt-3 mb-3 rounded\"\r\n");
      out.write("                             style=\"background-color: #ff6f0075; border-left: #FF6D00 solid 5px;\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-12 mt-3 mb-3\">\r\n");
      out.write("                                    <label class=\"form-label fs-5 fw-bold ps-4\">Notice :</label>\r\n");
      out.write("                                    <label class=\"form-label fs-5\">Purchased items can be return before 7 days of\r\n");
      out.write("                                        delivery.</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <hr class=\"\" style=\"border:1px solid #FF6D00 !important;\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 mb-3 text-center\">\r\n");
      out.write("                            <label class=\"form-label fs-6 text-black-50\">\r\n");
      out.write("                                Invoice was created in a computer and is valid without the Signature and Seal.\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"editor\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
