/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-10 18:04:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class singleproductview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/uvind/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
    _jspx_dependants.put("file:/C:/Users/uvind/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1692435033110L));
    _jspx_dependants.put("jar:file:/C:/Users/uvind/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/fn.tld", Long.valueOf(1602854172000L));
    _jspx_dependants.put("file:/C:/Users/uvind/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244256642L));
    _jspx_dependants.put("jar:file:/C:/Users/uvind/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602854172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/singleproductview.jsp(6,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/singleproductview.jsp(7,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("baseCss");
      // /WEB-INF/views/frontend/singleproductview.jsp(7,4) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setType("REPLACE");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f1 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f1);
    try {
      _jspx_th_layout_005fput_005f1.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f1.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/singleproductview.jsp(17,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f1.setBlock("contents");
      _jspx_th_layout_005fput_005f1.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_layout_005fput_005f1, null));
      _jspx_th_layout_005fput_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(new jakarta.servlet.jsp.tagext.TagAdapter((jakarta.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/views/frontend/singleproductview.jsp(586,32) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("i");
      // /WEB-INF/views/frontend/singleproductview.jsp(586,32) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(0);
      // /WEB-INF/views/frontend/singleproductview.jsp(586,32) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(5);
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                    <div class=\"product-card px-0 mx-0 mx-md-1\">\r\n");
            out.write("                                        <a href=\"singleproductview\" class=\"text-decoration-none\">\r\n");
            out.write("                                            <div class=\"card\">\r\n");
            out.write("                                                <img src=\"assets/images/products/Apple-12-Smartphones-491901535-i-1-1200Wx1200H-300Wx300H.jpg\"\r\n");
            out.write("                                                     class=\"product-card-img\" alt=\"...\">\r\n");
            out.write("                                                <div class=\"col-5 d-inline-block product-grid\">\r\n");
            out.write("                                                    <ul class=\"product-links\">\r\n");
            out.write("                                                        <li class=\"product-link-li\"><a href=\"wishlist\"\r\n");
            out.write("                                                                                       class=\"product-link-a\"><i\r\n");
            out.write("                                                                class=\"fa fa-heart\"></i></a></li>\r\n");
            out.write("                                                        <li class=\"product-link-li\"><a href=\"cart\"\r\n");
            out.write("                                                                                       class=\"product-link-a\"><i\r\n");
            out.write("                                                                class=\"fa fa-shopping-cart\"></i></a></li>\r\n");
            out.write("                                                    </ul>\r\n");
            out.write("                                                </div>\r\n");
            out.write("                                                <div class=\"card-body text-center\">\r\n");
            out.write("                                                    <h6 class=\"card-title text-black\">Huawei P30 Pro p30 p30 lite 128GB</h6>\r\n");
            out.write("                                                    <div class=\"mt-1\">\r\n");
            out.write("                                                        <ul class=\"d-flex list-unstyled mb-1 justify-content-center\">\r\n");
            out.write("                                                            <li><i class=\"fa fa-star rated\"></i></li>\r\n");
            out.write("                                                            <li><i class=\"fa fa-star rated\"></i></li>\r\n");
            out.write("                                                            <li><i class=\"fa fa-star rated\"></i></li>\r\n");
            out.write("                                                            <li><i class=\"fa fa-star rated\"></i></li>\r\n");
            out.write("                                                            <li><i class=\"fa fa-star\"></i></li>\r\n");
            out.write("                                                            <li><span class=\"text-success\">&nbsp;(899)</span>\r\n");
            out.write("                                                            </li>\r\n");
            out.write("                                                        </ul>\r\n");
            out.write("                                                    </div>\r\n");
            out.write("                                                    <button class=\"product-btn text-white\">\r\n");
            out.write("                                                        <span class=\"product-btn-text-one\">Rs.5000.00</span>\r\n");
            out.write("                                                        <span class=\"product-btn-text-two\">Buy Now</span>\r\n");
            out.write("                                                    </button>\r\n");
            out.write("                                                </div>\r\n");
            out.write("                                            </div>\r\n");
            out.write("                                        </a>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new jakarta.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f2(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f2 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f2);
    try {
      _jspx_th_layout_005fput_005f2.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f2.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/singleproductview.jsp(631,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f2.setBlock("baseStyle");
      // /WEB-INF/views/frontend/singleproductview.jsp(631,4) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f2.setType("REPLACE");
      _jspx_th_layout_005fput_005f2.setJspBody(new Helper( 3, _jspx_page_context, _jspx_th_layout_005fput_005f2, null));
      _jspx_th_layout_005fput_005f2.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f2);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f2(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\r');
      out.write('\n');
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" integrity=\"sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/frameworks/css/bootstrapV5.3.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/frameworks/css/style.css\">\r\n");
      out.write("        <!-- product zoom -->\r\n");
      out.write("        <script src=\"assets/frameworks/js/jquery.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"assets/frameworks/js/xzoom.min.js\"></script>\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/frameworks/css/xzoom.css\" media=\"all\" />\r\n");
      out.write("    ");
      return false;
    }
    public boolean invoke2( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <div class=\"container-fluid p-0\">\r\n");
      out.write("            <div class=\"row-fluid m-0\">\r\n");
      out.write("                <!-- BreadCrumb -->\r\n");
      out.write("                <div class=\"col-12 ps-4 my-3\">\r\n");
      out.write("                    <nav style=\"--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);\"\r\n");
      out.write("                         aria-label=\"breadcrumb\">\r\n");
      out.write("                        <ol class=\"breadcrumb mb-0\">\r\n");
      out.write("                            <li class=\"breadcrumb-item\"><a href=\"/newtech/\">Home</a></li>\r\n");
      out.write("                            <li class=\"breadcrumb-item\"><a href=\"productlistning\">Product Listning</a></li>\r\n");
      out.write("                            <li class=\"breadcrumb-item active\" aria-current=\"page\">Single Product View</li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"row d-flex justify-content-evenly mx-0\">\r\n");
      out.write("                        <div class=\"row m-0 px-0\">\r\n");
      out.write("                            <!-- Images section-->\r\n");
      out.write("                            <div class=\"col-xl-4 col-lg-5 col-md-6 mt-0 px-4\">\r\n");
      out.write("                                <section id=\"lens\">\r\n");
      out.write("                                    <div class=\"xzoom-container w-100\">\r\n");
      out.write("                                        <img class=\"xzoom3 img-fluid w-100\"\r\n");
      out.write("                                             src=\"assets/images/gallery/preview/01_b_car.jpg\"\r\n");
      out.write("                                             xoriginal=\"assets/images/gallery/original/01_b_car.jpg\"/>\r\n");
      out.write("                                        <div class=\"xzoom-thumbs mt-2 d-flex justify-content-center overflow-auto\">\r\n");
      out.write("                                            <a href=\"assets/images/gallery/original/01_b_car.jpg\"><img\r\n");
      out.write("                                                    class=\"xzoom-gallery3\" width=\"80\"\r\n");
      out.write("                                                    src=\"assets/images/gallery/thumbs/01_b_car.jpg\"\r\n");
      out.write("                                                    xpreview=\"assets/images/gallery/preview/01_b_car.jpg\"\r\n");
      out.write("                                                    title=\"The description goes here\"></a>\r\n");
      out.write("                                            <a href=\"assets/images/gallery/original/02_o_car.jpg\"><img\r\n");
      out.write("                                                    class=\"xzoom-gallery3\" width=\"80\"\r\n");
      out.write("                                                    src=\"assets/images/gallery/preview/02_o_car.jpg\"\r\n");
      out.write("                                                    title=\"The description goes here\"></a>\r\n");
      out.write("                                            <a href=\"assets/images/gallery/original/03_r_car.jpg\"><img\r\n");
      out.write("                                                    class=\"xzoom-gallery3\" width=\"80\"\r\n");
      out.write("                                                    src=\"assets/images/gallery/preview/03_r_car.jpg\"\r\n");
      out.write("                                                    title=\"The description goes here\"></a>\r\n");
      out.write("                                            <a href=\"assets/images/gallery/original/04_g_car.jpg\"><img\r\n");
      out.write("                                                    class=\"xzoom-gallery3\" width=\"80\"\r\n");
      out.write("                                                    src=\"assets/images/gallery/preview/04_g_car.jpg\"\r\n");
      out.write("                                                    title=\"The description goes here\"></a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </section>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Middle section -->\r\n");
      out.write("                            <div class=\"col-xl-4 col-lg-4 col-md-6 px-xl-5\">\r\n");
      out.write("                                <div class=\"row px-xl-5\">\r\n");
      out.write("                                    <div class=\"col-12\">\r\n");
      out.write("                                        <div class=\"row\">\r\n");
      out.write("                                            <div class=\"col-12 mb-0 text-start\">\r\n");
      out.write("                                                <div class=\"mb-0\"><span\r\n");
      out.write("                                                        class=\"text-uppercase text-muted brand\">Lenovo</span>\r\n");
      out.write("                                                    <h5 class=\"text-uppercase mb-0 fw-bold\">Lenovo Legion 5 Pro</h5>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"mx-1 d-inline-block\">\r\n");
      out.write("                                                    <li class=\"fa fa-star mt-1 text-warning fs-6\"></li>\r\n");
      out.write("                                                    <li class=\"fa fa-star mt-1 text-warning fs-6\"></li>\r\n");
      out.write("                                                    <li class=\"fa fa-star mt-1 text-warning fs-6\"></li>\r\n");
      out.write("                                                    <li class=\"fa fa-star mt-1 text-dark fs-6\"></li>\r\n");
      out.write("                                                    <li class=\"fa fa-star mt-1 text-dark fs-6\"></li>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <div class=\"mx-1 d-inline-block\">\r\n");
      out.write("                                                    <a href=\"#\" class=\"\">Read Reviews</a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div>\r\n");
      out.write("                                                    <span class=\"text-decoration-line-through text-danger\">Rs.200000</label></span>\r\n");
      out.write("                                                    <span>|20% off</span>\r\n");
      out.write("                                                    <span class=\"mx-1 fs-4\">Rs.160000.00</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-12 text-start mt-3 mt-md-3 mb-5 mb-md-0\">\r\n");
      out.write("                                                <div class=\"sizes mt-3\">\r\n");
      out.write("                                                    <h6 class=\"text-uppercase mx-0\">1.Color</h6> <label class=\"radio\">\r\n");
      out.write("                                                    <input class=\"\" type=\"radio\" name=\"size\" value=\"S\" checked> <span\r\n");
      out.write("                                                        class=\"me-2\">Grey</span> </label> <label class=\"radio\">\r\n");
      out.write("                                                    <input class=\"\" type=\"radio\" name=\"size\" value=\"M\"> <span\r\n");
      out.write("                                                        class=\"me-2\">Blue</span> </label><label class=\"radio\">\r\n");
      out.write("                                                    <input class=\"\" type=\"radio\" name=\"size\" value=\"L\"> <span\r\n");
      out.write("                                                        class=\"me-2\">Red</span> </label> <label class=\"radio\">\r\n");
      out.write("                                                    <input class=\"\" type=\"radio\" name=\"size\" value=\"XL\"> <span\r\n");
      out.write("                                                        class=\"me-2\"> Black</span> </label> <label class=\"radio\">\r\n");
      out.write("                                                    <input class=\"\" type=\"radio\" name=\"size\" value=\"XXL\"> <span\r\n");
      out.write("                                                        class=\"me-2\">White</span> </label>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"sizes mt-2\">\r\n");
      out.write("                                                    <h6 class=\"text-uppercase mx-0\">2.RAM</h6> <label class=\"radio\">\r\n");
      out.write("                                                    <input type=\"radio\" name=\"size\" value=\"S\" checked> <span\r\n");
      out.write("                                                        class=\"me-2\">4GB</span> </label> <label class=\"radio\">\r\n");
      out.write("                                                    <input type=\"radio\" name=\"size\" value=\"M\"> <span\r\n");
      out.write("                                                        class=\"me-2\">8GB</span> </label><label class=\"radio\">\r\n");
      out.write("                                                    <input type=\"radio\" name=\"size\" value=\"L\"> <span\r\n");
      out.write("                                                        class=\"me-2\">16GB</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"sizes mt-2\">\r\n");
      out.write("                                                    <h6 class=\"text-uppercase mx-0\">3.HardDrive</h6> <label\r\n");
      out.write("                                                        class=\"radio\">\r\n");
      out.write("                                                    <input type=\"radio\" name=\"size\" value=\"S\" checked> <span\r\n");
      out.write("                                                        class=\"me-2\">1TB SSD</span> </label> <label class=\"radio\">\r\n");
      out.write("                                                    <input type=\"radio\" name=\"size\" value=\"M\"> <span class=\"me-2\">1TB\r\n");
      out.write("                                                        SSD</span> </label><label class=\"radio\">\r\n");
      out.write("                                                    <input type=\"radio\" name=\"size\" value=\"L\"> <span class=\"me-2\">500GB\r\n");
      out.write("                                                        SSD + 500GB HDD</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <!-- About product summary -->\r\n");
      out.write("                                            <div class=\"col-12 mt-2 mt-md-5\">\r\n");
      out.write("                                                <div class=\"row\">\r\n");
      out.write("                                                    <div class=\"col-12 text-start\">\r\n");
      out.write("                                                    <span class=\"fs-5 bg-primary text-white\" style=\"font-weight: 500;\">&nbsp;Summary About\r\n");
      out.write("                                                        This Product:&nbsp;</span><br>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"col-12 d-flex justify-content-start\">\r\n");
      out.write("                                                        <ul class=\"mt-2\" style=\"list-style: disc;\">\r\n");
      out.write("                                                            <li><span class=\"text-primary\">Brand :</span>\r\n");
      out.write("                                                                <span>Lenovo</span><br>\r\n");
      out.write("                                                            </li>\r\n");
      out.write("                                                            <li><span class=\"text-primary\">Model:</span>\r\n");
      out.write("                                                                <span>Legion 5 15ACH6</span><br>\r\n");
      out.write("                                                            </li>\r\n");
      out.write("                                                            <li><span class=\"text-primary\">Colour:</span>\r\n");
      out.write("                                                                <span>Jet Black</span><br>\r\n");
      out.write("                                                            </li>\r\n");
      out.write("                                                            <li><span class=\"text-primary\">Deliver Fee\r\n");
      out.write("                                                                Within Colombo:</span>\r\n");
      out.write("                                                                <span>1000</span><br>\r\n");
      out.write("                                                            </li>\r\n");
      out.write("                                                            <li><span class=\"text-primary\">Deliver Fee Out\r\n");
      out.write("                                                                Of Colombo:</span>\r\n");
      out.write("                                                                <span>2000</span><br>\r\n");
      out.write("                                                            </li>\r\n");
      out.write("                                                        </ul>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- End section -->\r\n");
      out.write("                            <div class=\"col-xl-4 col-lg-3 col-md-12 mt-3 mt-lg-0\">\r\n");
      out.write("                                <div class=\"row p-xl-5 p-lg-0 p-md-4\">\r\n");
      out.write("                                    <div class=\"col-12 product-price-view-div p-3\">\r\n");
      out.write("                                        <div class=\"row\">\r\n");
      out.write("                                            <div class=\"col-12 mb-3\">\r\n");
      out.write("                                                <h5 class=\"text-danger\">\r\n");
      out.write("                                                    Rs.160000.00\r\n");
      out.write("                                                </h5>\r\n");
      out.write("                                                <p class=\"my-1\">&plus; Rs. 1000.00 Shipping</p>\r\n");
      out.write("                                                <p class=\"my-1\">&equals; Rs. 161000.00 <b class=\"text-primary\">Total</b>\r\n");
      out.write("                                                </p>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-12\">\r\n");
      out.write("                                                Est. Arrives : <b>July 20-26</b>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-12 mt-3\">\r\n");
      out.write("                                                <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\"\r\n");
      out.write("                                                     fill=\"currentColor\" class=\"bi bi-geo-alt\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                                    <path d=\"M12.166 8.94c-.524 1.062-1.234 2.12-1.96 3.07A31.493 31.493 0 0 1 8 14.58a31.481 31.481 0 0 1-2.206-2.57c-.726-.95-1.436-2.008-1.96-3.07C3.304 7.867 3 6.862 3 6a5 5 0 0 1 10 0c0 .862-.305 1.867-.834 2.94zM8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10z\"/>\r\n");
      out.write("                                                    <path d=\"M8 8a2 2 0 1 1 0-4 2 2 0 0 1 0 4zm0 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6z\"/>\r\n");
      out.write("                                                </svg>\r\n");
      out.write("                                                <a href=\"#\">Deliver to Sri Lanka</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-12 mb-1 d-grid lg-content  mt-4\">\r\n");
      out.write("                                                <button class=\"btn btn-outline-danger\"><i\r\n");
      out.write("                                                        class=\"bi bi-suit-heart-fill\"></i> Add to Wishlist\r\n");
      out.write("                                                </button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-12 mb-1 d-grid lg-content\">\r\n");
      out.write("                                                <button class=\"btn btn-outline-success\"><i class=\"bi bi-cart3\"></i> Add\r\n");
      out.write("                                                    to Chart\r\n");
      out.write("                                                </button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-12 mb-3 d-grid lg-content\">\r\n");
      out.write("                                                <button class=\"buy-btn\" id=\"payhere-payment\" type=\"submit\"><a\r\n");
      out.write("                                                        href=\"invoice\"\r\n");
      out.write("                                                        class=\"text-decoration-none link-light fw-bold\"><i\r\n");
      out.write("                                                        class=\"bi bi-bag-fill\"></i> Buy Now</a></button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-12 lh-1 mb-2\">\r\n");
      out.write("                                                <div class=\"row\">\r\n");
      out.write("                                                    <div class=\"col-4 text-center\">\r\n");
      out.write("                                                        <p><a href=\"#\" class=\"link-danger text-decoration-none\">100%\r\n");
      out.write("                                                            buyer satisfaction</a></p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"offset-1 col-3 text-center\">\r\n");
      out.write("                                                        <p>\r\n");
      out.write("                                                            <a href=\"#\"\r\n");
      out.write("                                                               class=\"link-success text-decoration-none\">100</a><br>\r\n");
      out.write("                                                            items left\r\n");
      out.write("                                                        </p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"offset-1 col-2 text-center\">\r\n");
      out.write("                                                        <p><a href=\"#\" class=\"link-success text-decoration-none\">216</a>\r\n");
      out.write("                                                            sold\r\n");
      out.write("                                                        </p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-12\">\r\n");
      out.write("                                                <p>Returns: Free 7 Day Returns | <a href=\"#\" class=\"fs-6\">see\r\n");
      out.write("                                                    details</a></p>\r\n");
      out.write("                                                <div class=\"d-flex\">\r\n");
      out.write("                                                    <p class=\"my-auto\">Payments:</p>\r\n");
      out.write("                                                    <div class=\"ms-4 mt-0\">\r\n");
      out.write("                                                        <img class=\"img-fluid\"\r\n");
      out.write("                                                             src=\"assets/images/paymentImages/american_express_img.png\"\r\n");
      out.write("                                                             alt=\"\">\r\n");
      out.write("                                                        <img class=\"img-fluid\"\r\n");
      out.write("                                                             src=\"assets/images/paymentImages/mastercard_img.png\"\r\n");
      out.write("                                                             alt=\"\">\r\n");
      out.write("                                                        <img class=\"img-fluid\"\r\n");
      out.write("                                                             src=\"assets/images/paymentImages/paypal_img.png\" alt=\"\">\r\n");
      out.write("                                                        <img class=\"img-fluid\"\r\n");
      out.write("                                                             src=\"assets/images/paymentImages/visa_img.png\" alt=\"\">\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Item specification -->\r\n");
      out.write("                <div class=\"col-12 mt-5\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12 px-5\">\r\n");
      out.write("                            <ul class=\"nav nav-tabs\" id=\"singleProductViewTabs\">\r\n");
      out.write("                                <li class=\"nav-item\">\r\n");
      out.write("                                    <a class=\"nav-link active\" data-toggle=\"tab\" href=\"#review\">Reviews</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"nav-item\">\r\n");
      out.write("                                    <a class=\"nav-link\" data-toggle=\"tab\" href=\"#productDetails\">Product Details</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"tab-content border border-1 row\">\r\n");
      out.write("                                <div id=\"review\" class=\"tab-pane fade show active\">\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        <div class=\"row clearfix g-2\">\r\n");
      out.write("                                            <div class=\"col-lg-4 col-md-12\">\r\n");
      out.write("                                                <div class=\"card\">\r\n");
      out.write("                                                    <div class=\"card-body\">\r\n");
      out.write("                                                        <h2 class=\" display-6 fw-bold mb-0\">4.5</h2>\r\n");
      out.write("                                                        <small class=\"text-muted\">based on 1,032 ratings</small>\r\n");
      out.write("                                                        <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                                        <span class=\"mb-2 me-3\">\r\n");
      out.write("                                                            <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                    class=\"bi bi-star-fill text-warning\"></i></a>\r\n");
      out.write("                                                            <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                    class=\"bi bi-star-fill text-warning\"></i></a>\r\n");
      out.write("                                                            <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                    class=\"bi bi-star-fill text-warning\"></i></a>\r\n");
      out.write("                                                            <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                    class=\"bi bi-star-fill text-warning\"></i></a>\r\n");
      out.write("                                                            <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                    class=\"bi bi-star-half text-warning\"></i></a>\r\n");
      out.write("                                                        </span>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"progress-count mt-2\">\r\n");
      out.write("                                                            <div class=\"d-flex justify-content-between align-items-center mb-1\">\r\n");
      out.write("                                                                <h6 class=\"mb-0 fw-bold d-flex align-items-center\">5<i\r\n");
      out.write("                                                                        class=\"bi bi-star-fill text-warning ms-1 small-11 pb-1\"></i>\r\n");
      out.write("                                                                </h6>\r\n");
      out.write("                                                                <span class=\"small text-muted\">661</span>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"progress\" style=\"height: 10px;\">\r\n");
      out.write("                                                                <div class=\"progress-bar\" role=\"progressbar\"\r\n");
      out.write("                                                                     style=\"width: 92%\" aria-valuenow=\"92\"\r\n");
      out.write("                                                                     aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"progress-count mt-2\">\r\n");
      out.write("                                                            <div class=\"d-flex justify-content-between align-items-center mb-1\">\r\n");
      out.write("                                                                <h6 class=\"mb-0 fw-bold d-flex align-items-center\">4<i\r\n");
      out.write("                                                                        class=\"bi bi-star-fill text-warning ms-1 small-11 pb-1\"></i>\r\n");
      out.write("                                                                </h6>\r\n");
      out.write("                                                                <span class=\"small text-muted\">237</span>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"progress\" style=\"height: 10px;\">\r\n");
      out.write("                                                                <div class=\"progress-bar\" role=\"progressbar\"\r\n");
      out.write("                                                                     style=\"width: 60%\" aria-valuenow=\"60\"\r\n");
      out.write("                                                                     aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"progress-count mt-2\">\r\n");
      out.write("                                                            <div class=\"d-flex justify-content-between align-items-center mb-1\">\r\n");
      out.write("                                                                <h6 class=\"mb-0 fw-bold d-flex align-items-center\">3<i\r\n");
      out.write("                                                                        class=\"bi bi-star-fill text-warning ms-1 small-11 pb-1\"></i>\r\n");
      out.write("                                                                </h6>\r\n");
      out.write("                                                                <span class=\"small text-muted\">76</span>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"progress\" style=\"height: 10px;\">\r\n");
      out.write("                                                                <div class=\"progress-bar\" role=\"progressbar\"\r\n");
      out.write("                                                                     style=\"width: 40%\" aria-valuenow=\"40\"\r\n");
      out.write("                                                                     aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"progress-count mt-2\">\r\n");
      out.write("                                                            <div class=\"d-flex justify-content-between align-items-center mb-1\">\r\n");
      out.write("                                                                <h6 class=\"mb-0 fw-bold d-flex align-items-center\">2<i\r\n");
      out.write("                                                                        class=\"bi bi-star-fill text-warning ms-1 small-11 pb-1\"></i>\r\n");
      out.write("                                                                </h6>\r\n");
      out.write("                                                                <span class=\"small text-muted\">19</span>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"progress\" style=\"height: 10px;\">\r\n");
      out.write("                                                                <div class=\"progress-bar\" role=\"progressbar\"\r\n");
      out.write("                                                                     style=\"width: 15%\" aria-valuenow=\"15\"\r\n");
      out.write("                                                                     aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"progress-count mt-2\">\r\n");
      out.write("                                                            <div class=\"d-flex justify-content-between align-items-center mb-1\">\r\n");
      out.write("                                                                <h6 class=\"mb-0 fw-bold d-flex align-items-center\">1<i\r\n");
      out.write("                                                                        class=\"bi bi-star-fill text-warning ms-1 small-11 pb-1\"></i>\r\n");
      out.write("                                                                </h6>\r\n");
      out.write("                                                                <span class=\"small text-muted\">39</span>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"progress\" style=\"height: 10px;\">\r\n");
      out.write("                                                                <div class=\"progress-bar\" role=\"progressbar\"\r\n");
      out.write("                                                                     style=\"width: 10%\" aria-valuenow=\"10\"\r\n");
      out.write("                                                                     aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"customer-like mt-5\">\r\n");
      out.write("                                                            <h6 class=\"mb-0 fw-bold \">What Customers Like</h6>\r\n");
      out.write("                                                            <ul class=\"list-group mt-3\">\r\n");
      out.write("                                                                <li class=\"list-group-item d-flex\">\r\n");
      out.write("                                                                    <div class=\"number border-end pe-2 fw-bold\">\r\n");
      out.write("                                                                        <strong class=\"color-light-success\">1</strong>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"cs-text flex-fill ps-2\">\r\n");
      out.write("                                                                        <span>Fun Factor</span>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"vote-text\">\r\n");
      out.write("                                                                        <span class=\"text-muted\">72 votes</span>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li class=\"list-group-item d-flex\">\r\n");
      out.write("                                                                    <div class=\"number border-end pe-2 fw-bold\">\r\n");
      out.write("                                                                        <strong class=\"color-light-success\">2</strong>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"cs-text flex-fill ps-2\">\r\n");
      out.write("                                                                        <span>Great Value</span>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"vote-text\">\r\n");
      out.write("                                                                        <span class=\"text-muted\">52 votes</span>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li class=\"list-group-item d-flex\">\r\n");
      out.write("                                                                    <div class=\"number border-end pe-2 fw-bold\">\r\n");
      out.write("                                                                        <strong class=\"color-light-success\">3</strong>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"cs-text flex-fill ps-2\">\r\n");
      out.write("                                                                        <span>eBazar</span>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"vote-text\">\r\n");
      out.write("                                                                        <span class=\"text-muted\">35 votes</span>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                            </ul>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"customer-like mt-5\">\r\n");
      out.write("                                                            <h6 class=\"mb-0 fw-bold \">What Need Improvement</h6>\r\n");
      out.write("                                                            <ul class=\"list-group mt-3\">\r\n");
      out.write("                                                                <li class=\"list-group-item d-flex\">\r\n");
      out.write("                                                                    <div class=\"number border-end pe-2 fw-bold\">\r\n");
      out.write("                                                                        <strong class=\"color-careys-pink\">1</strong>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"cs-text flex-fill ps-2\">\r\n");
      out.write("                                                                        <span>Value for Money</span>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"vote-text\">\r\n");
      out.write("                                                                        <span class=\"text-muted\">12 votes</span>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li class=\"list-group-item d-flex\">\r\n");
      out.write("                                                                    <div class=\"number border-end pe-2 fw-bold\">\r\n");
      out.write("                                                                        <strong class=\"color-careys-pink\">2</strong>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"cs-text flex-fill ps-2\">\r\n");
      out.write("                                                                        <span>Customer service</span>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"vote-text\">\r\n");
      out.write("                                                                        <span class=\"text-muted\">8 votes</span>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li class=\"list-group-item d-flex\">\r\n");
      out.write("                                                                    <div class=\"number border-end pe-2 fw-bold\">\r\n");
      out.write("                                                                        <strong class=\"color-careys-pink\">3</strong>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"cs-text flex-fill ps-2\">\r\n");
      out.write("                                                                        <span>Product Item</span>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"vote-text\">\r\n");
      out.write("                                                                        <span class=\"text-muted\">2 votes</span>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                            </ul>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-lg-8 col-md-12\">\r\n");
      out.write("                                                <ul class=\"list-unstyled mb-4\">\r\n");
      out.write("                                                    <li class=\"card mb-2\">\r\n");
      out.write("                                                        <div class=\"card-body p-lg-4 p-3\">\r\n");
      out.write("                                                            <div class=\"d-flex mb-3 pb-3 border-bottom flex-wrap\">\r\n");
      out.write("                                                                <img class=\"review-avatar rounded\"\r\n");
      out.write("                                                                     src=\"assets/images/userProfImgs/three.jpeg\" alt=\"\">\r\n");
      out.write("                                                                <div class=\"flex-fill ms-3 text-truncate\">\r\n");
      out.write("                                                                    <h6 class=\"mb-0\"><span>Joan Dyer</span></h6>\r\n");
      out.write("                                                                    <span class=\"text-muted\">3 hours ago</span>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                                                <span class=\"mb-2 me-3\">\r\n");
      out.write("                                                                    <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                            class=\"bi bi-star-fill text-warning\"></i></a>\r\n");
      out.write("                                                                    <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                            class=\"bi bi-star-fill text-warning\"></i></a>\r\n");
      out.write("                                                                    <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                            class=\"bi bi-star-fill text-warning\"></i></a>\r\n");
      out.write("                                                                    <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                            class=\"bi bi-star-fill text-warning\"></i></a>\r\n");
      out.write("                                                                    <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                            class=\"bi bi-star-half text-warning\"></i></a>\r\n");
      out.write("                                                                </span>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"timeline-item-post\">\r\n");
      out.write("                                                                <h6 class=\"\">Top-Oculus VR</h6>\r\n");
      out.write("                                                                <p> A good fit for many households, this Oculus VR has a\r\n");
      out.write("                                                                    movable deli drawer and door shelves that can\r\n");
      out.write("                                                                    accommodate gallon containers.Though its low price\r\n");
      out.write("                                                                    means fewer features, this pick is quiet and an\r\n");
      out.write("                                                                    energy-saving option, resulting in a lower energy\r\n");
      out.write("                                                                    bill.</p>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </li> <!-- .Card End -->\r\n");
      out.write("                                                    <li class=\"card mb-2\">\r\n");
      out.write("                                                        <div class=\"card-body p-lg-4 p-3\">\r\n");
      out.write("                                                            <div class=\"d-flex mb-3 pb-3 border-bottom flex-wrap\">\r\n");
      out.write("                                                                <img class=\"review-avatar rounded\"\r\n");
      out.write("                                                                     src=\"assets/images/userProfImgs/three.jpeg\" alt=\"\">\r\n");
      out.write("                                                                <div class=\"flex-fill ms-3 text-truncate\">\r\n");
      out.write("                                                                    <h6 class=\"mb-0\"><span>Phil Glover</span></h6>\r\n");
      out.write("                                                                    <span class=\"text-muted\">1 Day ago</span>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                                                <span class=\"mb-2 me-3\">\r\n");
      out.write("                                                                    <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                            class=\"bi bi-star-fill text-warning\"></i></a>\r\n");
      out.write("                                                                    <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                            class=\"bi bi-star-fill text-warning\"></i></a>\r\n");
      out.write("                                                                    <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                            class=\"bi bi-star-fill text-warning\"></i></a>\r\n");
      out.write("                                                                    <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                            class=\"bi bi-star-fill text-warning\"></i></a>\r\n");
      out.write("                                                                    <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                            class=\"bi bi-star-half text-warning\"></i></a>\r\n");
      out.write("                                                                </span>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"timeline-item-post\">\r\n");
      out.write("                                                                <h6 class=\"\">Oculus VR Full 3D</h6>\r\n");
      out.write("                                                                <p>I purchased this Oculus from elsewhere, on last\r\n");
      out.write("                                                                    Dipawali. As this Oculus contains in-built DDB(\r\n");
      out.write("                                                                    means you need not to install a separate set-top\r\n");
      out.write("                                                                    box), there is less number of wire hanging around\r\n");
      out.write("                                                                    the set and single remote required. Great full HD\r\n");
      out.write("                                                                    picture quality. Sound quality of the set is far\r\n");
      out.write("                                                                    better than most of the sets of the so called big\r\n");
      out.write("                                                                    brands.</p>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </li> <!-- .Card End -->\r\n");
      out.write("                                                    <li class=\"card mb-2\">\r\n");
      out.write("                                                        <div class=\"card-body p-lg-4 p-3\">\r\n");
      out.write("                                                            <div class=\"d-flex mb-3 pb-3 border-bottom flex-wrap\">\r\n");
      out.write("                                                                <img class=\"review-avatar rounded\"\r\n");
      out.write("                                                                     src=\"assets/images/userProfImgs/three.jpeg\" alt=\"\">\r\n");
      out.write("                                                                <div class=\"flex-fill ms-3 text-truncate\">\r\n");
      out.write("                                                                    <h6 class=\"mb-0\"><span>Victor Rampling</span></h6>\r\n");
      out.write("                                                                    <span class=\"text-muted\">5 Day ago</span>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                                                <span class=\"mb-2 me-3\">\r\n");
      out.write("                                                                    <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                            class=\"bi bi-star-fill text-warning\"></i></a>\r\n");
      out.write("                                                                    <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                            class=\"bi bi-star-fill text-warning\"></i></a>\r\n");
      out.write("                                                                    <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                            class=\"bi bi-star-fill text-warning\"></i></a>\r\n");
      out.write("                                                                    <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                            class=\"bi bi-star-fill text-warning\"></i></a>\r\n");
      out.write("                                                                    <a href=\"#\" class=\"rating-link active\"><i\r\n");
      out.write("                                                                            class=\"bi bi-star-half text-warning\"></i></a>\r\n");
      out.write("                                                                </span>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"timeline-item-post\">\r\n");
      out.write("                                                                <h6 class=\"\">Oculus VR Wireless Bluetooth</h6>\r\n");
      out.write("                                                                <p>The build quality feels really premium.Sound quality\r\n");
      out.write("                                                                    is quite great compared to its price point.Sound\r\n");
      out.write("                                                                    quality is quite great compared to its price\r\n");
      out.write("                                                                    point.</p>\r\n");
      out.write("                                                                <div>\r\n");
      out.write("                                                                    <div class=\"d-flex mt-3 pt-3 border-top\">\r\n");
      out.write("                                                                        <img class=\"avatar rounded\"\r\n");
      out.write("                                                                             src=\"assets/images/xs/avatar12.svg\" alt=\"\">\r\n");
      out.write("                                                                        <div class=\"flex-fill ms-3 text-truncate\">\r\n");
      out.write("                                                                            <p class=\"mb-0\"><span>Karen Clark</span>\r\n");
      out.write("                                                                                <small class=\"msg-time text-muted\">5 Day\r\n");
      out.write("                                                                                    ago</small></p>\r\n");
      out.write("                                                                            <span class=\"text-muted\">Hd quality is quite great compared to its price point.</span>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"mt-4\">\r\n");
      out.write("                                                                    <textarea class=\"form-control\"\r\n");
      out.write("                                                                              placeholder=\"Replay\"></textarea>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </li> <!-- .Card End -->\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                                <nav aria-label=\"...\">\r\n");
      out.write("                                                    <ul class=\"pagination justify-content-end\">\r\n");
      out.write("                                                        <li class=\"page-item disabled\">\r\n");
      out.write("                                                            <span class=\"page-link\">Previous</span>\r\n");
      out.write("                                                        </li>\r\n");
      out.write("                                                        <li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("                                                        <li class=\"page-item active\" aria-current=\"page\">\r\n");
      out.write("                                                            <span class=\"page-link\">2</span>\r\n");
      out.write("                                                        </li>\r\n");
      out.write("                                                        <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("                                                        <li class=\"page-item\">\r\n");
      out.write("                                                            <a class=\"page-link\" href=\"#\">Next</a>\r\n");
      out.write("                                                        </li>\r\n");
      out.write("                                                    </ul>\r\n");
      out.write("                                                </nav>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"productDetails\" class=\"tab-pane fade\">\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        lorem1000\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Recomended -->\r\n");
      out.write("                <div class=\"col-12 px-4 mt-5\">\r\n");
      out.write("                    <div class=\"row mx-0\">\r\n");
      out.write("                        <!-- product head -->\r\n");
      out.write("                        <div class=\"col-12 product-space position-relative px-0 mb-4\">\r\n");
      out.write("                            <span class=\"\">Recomended to You</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- product body -->\r\n");
      out.write("                        <div class=\"col-12 px-0 mb-4\">\r\n");
      out.write("                            <div class=\"row mx-0  px-0 justify-content-between\">\r\n");
      out.write("                                ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    ");
      return false;
    }
    public boolean invoke3( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            function change_image(image) {\r\n");
      out.write("\r\n");
      out.write("                var container = document.getElementById(\"main-image\");\r\n");
      out.write("\r\n");
      out.write("                container.src = image.src;\r\n");
      out.write("            }\r\n");
      out.write("            document.addEventListener(\"DOMContentLoaded\", function(event) {});\r\n");
      out.write("\r\n");
      out.write("            $(document).ready(function() {\r\n");
      out.write("                $(\"#singleProductViewTabs a\").click(function(e) {\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("                    $(this).tab('show');\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("        <script src=\"assets/frameworks/js/script.js\"></script>\r\n");
      out.write("        <script src=\"assets/frameworks/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- product zoom -->\r\n");
      out.write("        <script src=\"assets/frameworks/js/setup.js\"></script>\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
          case 3:
            invoke3( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
