/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-10 18:05:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class userAccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/uvind/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
    _jspx_dependants.put("file:/C:/Users/uvind/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1692435033110L));
    _jspx_dependants.put("jar:file:/C:/Users/uvind/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/fn.tld", Long.valueOf(1602854172000L));
    _jspx_dependants.put("file:/C:/Users/uvind/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244256642L));
    _jspx_dependants.put("jar:file:/C:/Users/uvind/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602854172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/userAccount.jsp(6,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/userAccount.jsp(7,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("contents");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\r');
      out.write('\n');
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <div class=\"container-fluid p-0\">\r\n");
      out.write("            <div class=\"row-fluid m-0\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"row mx-0\">\r\n");
      out.write("                        <!-- BreadCrumb -->\r\n");
      out.write("                        <div class=\"text-center mt-3\">\r\n");
      out.write("                            <div class=\"col-12 ps-4 mt-3\">\r\n");
      out.write("                                <nav style=\"--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);\" aria-label=\"breadcrumb\">\r\n");
      out.write("                                    <ol class=\"breadcrumb mb-0\">\r\n");
      out.write("                                        <li class=\"breadcrumb-item\"><a href=\"/newtech/\">Home</a></li>\r\n");
      out.write("                                        <li class=\"breadcrumb-item active\" aria-current=\"page\">MyAccount</li>\r\n");
      out.write("                                    </ol>\r\n");
      out.write("                                </nav>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <span class=\"fw-bold fs-3\"><i class=\"bi bi-person-bounding-box\"></i> My Account</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-lg-3 col-md-4 col-sm-5 col-12 mb-2\">\r\n");
      out.write("                                    <div class=\"card my-2\">\r\n");
      out.write("                                        <div class=\"card-header d-flex justify-content-between icon-link\">\r\n");
      out.write("                                            <span class=\"\">Profile</span>\r\n");
      out.write("                                            <button class=\"btn btn-sm btn-outline-danger\">Logout <i class=\"bi bi-box-arrow-right\"></i></button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"card-body\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-12 text-center\">\r\n");
      out.write("                                                    <img src=\"assets/images/userProfImgs/three.jpeg\" class=\"img-thumbnail\" style=\"width: 100px; height: 100px;\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-12 mt-2\">\r\n");
      out.write("                                                    <span><i class=\"bi bi-person-lines-fill\"></i> Mr.Rashmika Jayasooriya</span>\r\n");
      out.write("                                                    <br /><span><i class=\"bi bi-calendar-event\"></i> 2001/04/05</span>\r\n");
      out.write("                                                    <br /><span><i class=\"bi bi-telephone-fill\"></i> 202-555-0174</span>\r\n");
      out.write("                                                    <br /><span><i class=\"bi bi-envelope-fill\"></i> adrianallan@gmail.com</span>\r\n");
      out.write("                                                    <br /><span><i class=\"bi bi-signpost-fill\"></i> 2734 West Fork Street,EASTON 02334.</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"card-footer\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-12\">\r\n");
      out.write("                                                    <a href=\"#\" class=\"icon-link icon-link-hover link-underline link-underline-opacity-0\"><i class=\"icon-link bi bi-suit-heart-fill\"></i> My Wishlist</a><br />\r\n");
      out.write("                                                    <a href=\"#\" class=\"icon-link icon-link-hover link-underline link-underline-opacity-0\"><i class=\"icon-link bi bi-cart3\"></i> My Cart</a><br />\r\n");
      out.write("                                                    <a href=\"#\" class=\"icon-link icon-link-hover link-underline link-underline-opacity-0\"><i class=\"icon-link bi bi-truck\"></i> My Orders</a><br />\r\n");
      out.write("                                                    <a href=\"#\" class=\"icon-link icon-link-hover link-underline link-underline-opacity-0\"><i class=\"bi bi-clock-history\"></i> My Purchase History</a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"card\">\r\n");
      out.write("                                        <div class=\"card-header\">\r\n");
      out.write("                                            <span>Payment Method</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"card-body\">\r\n");
      out.write("                                            <i class=\"bi bi-credit-card-2-back fs-3\"></i><span> Visa *******7548</span></br>\r\n");
      out.write("                                            <span>Next billing charged $48</span><br />\r\n");
      out.write("                                            <span>Autopay on July 20, 2021</span><a href=\"#\" class=\"link-warning text-decoration-none ms-2\" style=\"font-size: 14px;\">Edit Payment Info</a><br />\r\n");
      out.write("                                            <button class=\"btn btn-primary btn-sm mt-1\">Add Payment Info</button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-lg-9 col-md-8 col-sm-7 col-12 mb-2\">\r\n");
      out.write("                                    <div class=\"card my-2\">\r\n");
      out.write("                                        <div class=\"card-header\">\r\n");
      out.write("                                            <span>Profile Settings</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"card-body\">\r\n");
      out.write("                                            <div class=\"accordion\" id=\"accordionExample\">\r\n");
      out.write("                                                <div class=\"accordion-item\">\r\n");
      out.write("                                                    <h2 class=\"accordion-header\">\r\n");
      out.write("                                                        <button class=\"accordion-button text-primary\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseOne\" aria-expanded=\"true\" aria-controls=\"collapseOne\">\r\n");
      out.write("                                                            Account Detalis\r\n");
      out.write("                                                        </button>\r\n");
      out.write("                                                    </h2>\r\n");
      out.write("                                                    <div id=\"collapseOne\" class=\"accordion-collapse collapse show\" data-bs-parent=\"#accordionExample\">\r\n");
      out.write("                                                        <div class=\"accordion-body\">\r\n");
      out.write("                                                            <div class=\"row g-3\">\r\n");
      out.write("                                                                <div class=\"col-md-6\">\r\n");
      out.write("                                                                    <label for=\"\" class=\"form-label\">First Name</label>\r\n");
      out.write("                                                                    <input type=\"text\" class=\"form-control\" id=\"\">\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"col-md-6\">\r\n");
      out.write("                                                                    <label for=\"\" class=\"form-label\">Last Name</label>\r\n");
      out.write("                                                                    <input type=\"text\" class=\"form-control\" id=\"\">\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"col-md-6\">\r\n");
      out.write("                                                                    <label for=\"inputEmail4\" class=\"form-label\">Email</label>\r\n");
      out.write("                                                                    <input type=\"email\" class=\"form-control\" id=\"inputEmail4\">\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"col-md-6\">\r\n");
      out.write("                                                                    <label for=\"inputPassword4\" class=\"form-label\">Password</label>\r\n");
      out.write("                                                                    <input type=\"password\" class=\"form-control\" id=\"inputPassword4\">\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"col-6\">\r\n");
      out.write("                                                                    <label for=\"\" class=\"form-label\">Date Of Birth</label>\r\n");
      out.write("                                                                    <input type=\"date\" class=\"form-control\" id=\"\" placeholder=\"\">\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"col-6\">\r\n");
      out.write("                                                                    <label for=\"\" class=\"form-label\">Mobile No.</label>\r\n");
      out.write("                                                                    <input type=\"text\" class=\"form-control\" id=\"\" placeholder=\"\">\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12\">\r\n");
      out.write("                                                                    <button type=\"submit\" class=\"btn btn-sm btn-success mt-2\">Update Details</button>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"accordion-item\">\r\n");
      out.write("                                                    <h2 class=\"accordion-header\">\r\n");
      out.write("                                                        <button class=\"accordion-button text-primary collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseTwo\" aria-expanded=\"false\" aria-controls=\"collapseTwo\">\r\n");
      out.write("                                                            Change Password\r\n");
      out.write("                                                        </button>\r\n");
      out.write("                                                    </h2>\r\n");
      out.write("                                                    <div id=\"collapseTwo\" class=\"accordion-collapse collapse\" data-bs-parent=\"#accordionExample\">\r\n");
      out.write("                                                        <div class=\"accordion-body\">\r\n");
      out.write("                                                            <div class=\"row g-3\">\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-md-6\">\r\n");
      out.write("                                                                    <label for=\"inputPassword4\" class=\"form-label\">Current Password</label>\r\n");
      out.write("                                                                    <input type=\"password\" class=\"form-control\" id=\"inputPassword4\">\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"col-md-6\">\r\n");
      out.write("                                                                    <label for=\"inputPassword4\" class=\"form-label\">New Password</label>\r\n");
      out.write("                                                                    <input type=\"password\" class=\"form-control\" id=\"inputPassword4\">\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"col-md-6\">\r\n");
      out.write("                                                                    <label for=\"inputPassword4\" class=\"form-label\">Confirm New Password</label>\r\n");
      out.write("                                                                    <input type=\"password\" class=\"form-control\" id=\"inputPassword4\">\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12\">\r\n");
      out.write("                                                                    <button type=\"submit\" class=\"btn btn-sm btn-success mt-2\">Update Password</button>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"accordion-item\">\r\n");
      out.write("                                                    <h2 class=\"accordion-header\">\r\n");
      out.write("                                                        <button class=\"accordion-button collapsed text-primary\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseThree\" aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("                                                            Addresses\r\n");
      out.write("                                                        </button>\r\n");
      out.write("                                                    </h2>\r\n");
      out.write("                                                    <div id=\"collapseThree\" class=\"accordion-collapse collapse\" data-bs-parent=\"#accordionExample\">\r\n");
      out.write("                                                        <div class=\"accordion-body\">\r\n");
      out.write("                                                            <div class=\"row\">\r\n");
      out.write("                                                                <div class=\"col-12 border border-1 p-3\">\r\n");
      out.write("                                                                    <div class=\"row g-3\">\r\n");
      out.write("                                                                        <div>\r\n");
      out.write("                                                                            <span>Billing Address</span>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-md-6\">\r\n");
      out.write("                                                                            <label for=\"\" class=\"form-label\">Name</label>\r\n");
      out.write("                                                                            <input type=\"text\" class=\"form-control\" id=\"\">\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-12\">\r\n");
      out.write("                                                                            <label for=\"inputAddress\" class=\"form-label\">Address</label>\r\n");
      out.write("                                                                            <input type=\"text\" class=\"form-control\" id=\"inputAddress\" placeholder=\"1234 Main St\">\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-12\">\r\n");
      out.write("                                                                            <label for=\"inputAddress2\" class=\"form-label\">Address 2</label>\r\n");
      out.write("                                                                            <input type=\"text\" class=\"form-control\" id=\"inputAddress2\" placeholder=\"Apartment, studio, or floor\">\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-md-6\">\r\n");
      out.write("                                                                            <label for=\"inputCity\" class=\"form-label\">City</label>\r\n");
      out.write("                                                                            <input type=\"text\" class=\"form-control\" id=\"inputCity\">\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-md-4\">\r\n");
      out.write("                                                                            <label for=\"inputState\" class=\"form-label\">State</label>\r\n");
      out.write("                                                                            <select id=\"inputState\" class=\"form-select\">\r\n");
      out.write("                                                                                <option selected>Choose...</option>\r\n");
      out.write("                                                                                <option>...</option>\r\n");
      out.write("                                                                            </select>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-md-2\">\r\n");
      out.write("                                                                            <label for=\"inputZip\" class=\"form-label\">Zip</label>\r\n");
      out.write("                                                                            <input type=\"text\" class=\"form-control\" id=\"inputZip\">\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                                                        <div class=\"col-12\">\r\n");
      out.write("                                                                            <button type=\"submit\" class=\"btn btn-sm btn-success mt-2\">Update Billing Address</button>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"col-12  border border-1 p-3 mt-1\">\r\n");
      out.write("                                                                    <div class=\"row g-3\">\r\n");
      out.write("                                                                        <div>\r\n");
      out.write("                                                                            <span>Shipping Address</span>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-md-6\">\r\n");
      out.write("                                                                            <label for=\"\" class=\"form-label\">Name</label>\r\n");
      out.write("                                                                            <input type=\"text\" class=\"form-control\" id=\"\">\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-12\">\r\n");
      out.write("                                                                            <label for=\"inputAddress\" class=\"form-label\">Address</label>\r\n");
      out.write("                                                                            <input type=\"text\" class=\"form-control\" id=\"inputAddress\" placeholder=\"1234 Main St\">\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-12\">\r\n");
      out.write("                                                                            <label for=\"inputAddress2\" class=\"form-label\">Address 2</label>\r\n");
      out.write("                                                                            <input type=\"text\" class=\"form-control\" id=\"inputAddress2\" placeholder=\"Apartment, studio, or floor\">\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-md-6\">\r\n");
      out.write("                                                                            <label for=\"inputCity\" class=\"form-label\">City</label>\r\n");
      out.write("                                                                            <input type=\"text\" class=\"form-control\" id=\"inputCity\">\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-md-4\">\r\n");
      out.write("                                                                            <label for=\"inputState\" class=\"form-label\">State</label>\r\n");
      out.write("                                                                            <select id=\"inputState\" class=\"form-select\">\r\n");
      out.write("                                                                                <option selected>Choose...</option>\r\n");
      out.write("                                                                                <option>...</option>\r\n");
      out.write("                                                                            </select>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-md-2\">\r\n");
      out.write("                                                                            <label for=\"inputZip\" class=\"form-label\">Zip</label>\r\n");
      out.write("                                                                            <input type=\"text\" class=\"form-control\" id=\"inputZip\">\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                                                        <div class=\"col-12\">\r\n");
      out.write("                                                                            <button type=\"submit\" class=\"btn btn-sm btn-success mt-2\">Update Shipping Address</button>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
