/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-10 19:37:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.layout;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class base_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/uvind/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
    _jspx_dependants.put("file:/C:/Users/uvind/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244256642L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"author\" content=\"D.U.R.P. Jayasooriya\">\r\n");
      out.write("    <title>New-Tech | Home</title>\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fblock_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"scrollbar\" onload=\"toast();\">\r\n");
      out.write("<div class=\"container-fluid p-0 overflow-hidden\">\r\n");
      out.write("    <div class=\"row-fluid m-0\">\r\n");
      out.write("        <!-- sales strip -->\r\n");
      out.write("        <div class=\"col-12\">\r\n");
      out.write("            <img src=\"assets/images/salesStrip/topSaleStrip.jpg\" alt=\"sale\" class=\"ratio ratio-21x9\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- header start -->\r\n");
      out.write("        <header>\r\n");
      out.write("            <div class=\"col-12\">\r\n");
      out.write("                <div class=\"row mx-0\">\r\n");
      out.write("                    <!-- User Strip Start -->\r\n");
      out.write("                    <div class=\"col-12 user-strip\">\r\n");
      out.write("                        <div class=\"row d-flex flex-row float-end text-nowrap\">\r\n");
      out.write("                            <div class=\"col order-sm-2\">\r\n");
      out.write("                                <ul class=\"list-unstyled d-flex gap-3 m-0 py-2 justify-content-center\">\r\n");
      out.write("                                    <li><a href=\"useraccount\" class=\"text-white text-decoration-none\"><i\r\n");
      out.write("                                            class=\"icon fa fa-user\"></i>My Account</a></li>\r\n");
      out.write("                                    <li><a href=\"wishlist\" class=\"text-white text-decoration-none\"><i\r\n");
      out.write("                                            class=\"icon fa fa-heart\"></i>Wishlist</a></li>\r\n");
      out.write("                                    <li><a href=\"cart\" class=\"text-white text-decoration-none\"><i\r\n");
      out.write("                                            class=\"icon fa fa-shopping-cart\"></i>My Cart</a></li>\r\n");
      out.write("                                    <li><a href=\"purchasehistory\"\r\n");
      out.write("                                           class=\"text-white text-decoration-none d-none d-sm-block\"><i\r\n");
      out.write("                                            class=\"icon fa fa-check\"></i>Purchased History</a></li>\r\n");
      out.write("                                    <li><a href=\"login\" class=\"text-white text-decoration-none d-none d-sm-block\"><i\r\n");
      out.write("                                            class=\"icon fa fa-lock\"></i>Login</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col\">\r\n");
      out.write("                                <ul class=\"list-unstyled d-flex justify-content-center gap-2 m-0 py-2\">\r\n");
      out.write("                                    <li class=\"dropdown dropdown-small\">\r\n");
      out.write("                                        <a href=\"#\" class=\"dropdown-toggle text-white text-decoration-none\"\r\n");
      out.write("                                           data-bs-hover=\"dropdown\" data-bs-toggle=\"dropdown\"><span>LKR</span></a>\r\n");
      out.write("                                        <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-dark\"\r\n");
      out.write("                                            style=\"max-width: 200px !important; min-width: 10px !important;\">\r\n");
      out.write("                                            <li><a href=\"#\" class=\"dropdown-item text-white\">LKR</a></li>\r\n");
      out.write("                                            <li><a href=\"#\" class=\"dropdown-item text-white\">USD</a></li>\r\n");
      out.write("                                            <li><a href=\"#\" class=\"dropdown-item text-white\">GBP</a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"dropdown dropdown-small\">\r\n");
      out.write("                                        <a href=\"#\" class=\"dropdown-toggle text-white text-decoration-none\"\r\n");
      out.write("                                           data-bs-hover=\"dropdown\" data-bs-toggle=\"dropdown\"><span>English\r\n");
      out.write("                                                </span></a>\r\n");
      out.write("                                        <ul class=\"dropdown-menu  dropdown-menu-end dropdown-menu-dark\"\r\n");
      out.write("                                            style=\"max-width: 200px !important; min-width: 10px !important;\">\r\n");
      out.write("                                            <li><a href=\"#\" class=\"dropdown-item text-white\">English</a></li>\r\n");
      out.write("                                            <li><a href=\"#\" class=\"dropdown-item text-white\">Russian</a></li>\r\n");
      out.write("                                            <li><a href=\"#\" class=\"dropdown-item text-white\">German</a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- USer Strip End -->\r\n");
      out.write("                    <!-- Header Start -->\r\n");
      out.write("                    <div class=\"col-12 col-sm-11 col-md-12 header-row\">\r\n");
      out.write("                        <div class=\"row mt-1\">\r\n");
      out.write("                            <div class=\"offset-0 offset-md-0 col-8 col-sm-4 col-md-2 pt-0 text-center order-1 header-logo-container\">\r\n");
      out.write("                                <img src=\"assets/images/logo/New Tech (5).png\" alt=\"logo\" class=\"img-fluid\"/>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-12 col-sm-6 col-md-7 mt-sm-3 pt-2 order-4 order-sm-2 header-searchfield-container\">\r\n");
      out.write("                                <div class=\"input-group mb-md-3 position-relative\">\r\n");
      out.write("                                    <button class=\"dropdown-toggle searchfield-category  d-none d-sm-block fs-6\"\r\n");
      out.write("                                            type=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">All Category\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"#\">Laptops</a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"#\">Cellphones</a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"#\">Camera</a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"#\">Drones</a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"#\">Consoles</a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"#\">Smart Home</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control searchfield-text\"/>\r\n");
      out.write("                                    <a href=\"advancedsearch\"\r\n");
      out.write("                                       class=\"text-decoration-none rounded-0 position-absolute\"\r\n");
      out.write("                                       style=\"right: 42px; top: 0;\"><span\r\n");
      out.write("                                            class=\"input-group-text searchfield-btn bg-white text-dark rounded-0\"\r\n");
      out.write("                                            style=\"font-size: 10px; line-height: 12px;\">Advanced</br>\r\n");
      out.write("                                        Search</span></a>\r\n");
      out.write("                                    <span class=\"input-group-text btn searchfield-btn position-absolute\"\r\n");
      out.write("                                          style=\"right: 0px; top: 0px;\"><i class=\"icon fa fa-search\"></i></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-2 col-sm-1 col-md-3 order-2 order-sm-3 header-minicart-container\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"minicart-div\">\r\n");
      out.write("                                            <span class=\"minicart-icon\">\r\n");
      out.write("                                                <img src=\"assets/images/header/cart.png\" alt=\"\" width=\"50\" height=\"50\"\r\n");
      out.write("                                                     class=\"img-fluid\"/>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        <span class=\"minicart-num\" id=\"topActionCartNumber\"\r\n");
      out.write("                                              style=\"display: block;\">2</span>\r\n");
      out.write("                                        <div class=\"d-inline d-md-none ms-5\">\r\n");
      out.write("                                            <button class=\"navbar-toggler position-absolute ms-0 mt-2 toggle-btn shadow-none p-0\"\r\n");
      out.write("                                                    type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("                                                    data-bs-target=\"#navbarScroll\" aria-controls=\"navbarScroll\"\r\n");
      out.write("                                                    aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                                                <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\"\r\n");
      out.write("                                                     fill=\"currentColor\" class=\"bi bi-list\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                                    <path fill-rule=\"evenodd\"\r\n");
      out.write("                                                          d=\"M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z\"/>\r\n");
      out.write("                                                </svg>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"minicart-price-div d-none d-md-block\">\r\n");
      out.write("                                        <div class=\"row\">\r\n");
      out.write("                                            <div class=\"col-12 p-0 pt-1\">\r\n");
      out.write("                                                <span class=\"fw-bold minicart-price-text\">Your Cart</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-12 p-0\">\r\n");
      out.write("                                                <span class=\"minicart-price\">$0.00</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Header End -->\r\n");
      out.write("                    <!-- Responsive Navbar Start -->\r\n");
      out.write("                    <div class=\"col-12 px-0\">\r\n");
      out.write("                        <div class=\"row mx-0\">\r\n");
      out.write("                            <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("                                <div class=\"container-fluid px-0\">\r\n");
      out.write("                                    <div class=\"collapse navbar-collapse row position-relative mx-0\" id=\"navbarScroll\">\r\n");
      out.write("                                        <ul class=\"navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll col-12 justify-content-between\"\r\n");
      out.write("                                            style=\"--bs-scroll-height: 200px;\">\r\n");
      out.write("                                            <li class=\"nav-item\">\r\n");
      out.write("                                                <a class=\"nav-link nav-active\" aria-current=\"page\" href=\"#\">Home</a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"nav-item dropdown\" onmouseenter=\"drop();\">\r\n");
      out.write("                                                <a class=\"nav-link dropdown-toggle\" href=\"#\"\r\n");
      out.write("                                                   id=\"navbarScrollingDropdown\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                                                   aria-expanded=\"false\">\r\n");
      out.write("                                                    Laptop & Accessories\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                                <ul class=\"dropdown-menu menu\"\r\n");
      out.write("                                                    aria-labelledby=\"navbarScrollingDropdown\">\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Asus</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">MSI</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Lenovo</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Dell</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">HP</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Dynabook</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Apple</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"nav-item dropdown\">\r\n");
      out.write("                                                <a class=\"nav-link dropdown-toggle\" href=\"#\"\r\n");
      out.write("                                                   id=\"navbarScrollingDropdown\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                                                   aria-expanded=\"false\">\r\n");
      out.write("                                                    Cellphones & Accessories\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                                <ul class=\"dropdown-menu menu\"\r\n");
      out.write("                                                    aria-labelledby=\"navbarScrollingDropdown\">\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Samsung</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Xiaomi</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Huawei</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Razor</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"nav-item dropdown\">\r\n");
      out.write("                                                <a class=\"nav-link dropdown-toggle\" href=\"#\"\r\n");
      out.write("                                                   id=\"navbarScrollingDropdown\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                                                   aria-expanded=\"false\">\r\n");
      out.write("                                                    Cameras\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                                <ul class=\"dropdown-menu menu\"\r\n");
      out.write("                                                    aria-labelledby=\"navbarScrollingDropdown\">\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Nikon</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Canon</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Fujifilm</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Sony</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"nav-item dropdown\">\r\n");
      out.write("                                                <a class=\"nav-link dropdown-toggle\" href=\"#\"\r\n");
      out.write("                                                   id=\"navbarScrollingDropdown\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                                                   aria-expanded=\"false\">\r\n");
      out.write("                                                    Drones\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                                <ul class=\"dropdown-menu menu\"\r\n");
      out.write("                                                    aria-labelledby=\"navbarScrollingDropdown\">\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">DJI</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Yuneec</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Kespry.</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Autel\r\n");
      out.write("                                                        Robotics</a></li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"nav-item dropdown\">\r\n");
      out.write("                                                <a class=\"nav-link dropdown-toggle\" href=\"#\"\r\n");
      out.write("                                                   id=\"navbarScrollingDropdown\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                                                   aria-expanded=\"false\">\r\n");
      out.write("                                                    Video Game Consoles\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                                <ul class=\"dropdown-menu menu\"\r\n");
      out.write("                                                    aria-labelledby=\"navbarScrollingDropdown\">\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\"\r\n");
      out.write("                                                           href=\"productlistning\">Microsoft</a></li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Sony</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Nintendo</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Sega</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"nav-item dropdown\">\r\n");
      out.write("                                                <a class=\"nav-link dropdown-toggle\" href=\"#\"\r\n");
      out.write("                                                   id=\"navbarScrollingDropdown\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                                                   aria-expanded=\"false\">\r\n");
      out.write("                                                    Smart Home\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                                <ul class=\"dropdown-menu menu\"\r\n");
      out.write("                                                    aria-labelledby=\"navbarScrollingDropdown\">\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Nest</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\"\r\n");
      out.write("                                                           href=\"productlistning\">SmartThings</a></li>\r\n");
      out.write("                                                    <li><a class=\"dropdown-item\" href=\"productlistning\">Philips\r\n");
      out.write("                                                        Hue</a></li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </nav>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Responsive Navbar End -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- header end -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Body Start -->\r\n");
      out.write("        ");
      if (_jspx_meth_layout_005fblock_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        <!-- Body End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Footter Start -->\r\n");
      out.write("        <div class=\"col-12\">\r\n");
      out.write("            <footer class=\"text-light pt-5 pb-4 sticky-footer footer\">\r\n");
      out.write("                <div class=\"row mx-0\">\r\n");
      out.write("                    <div class=\"col-12 px-5 mb-3\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-12 text-center mb-4\" style=\"line-height: 10px;\">\r\n");
      out.write("                                <p class=\"text-light fs-4 fw-bold lh-1\">SUBSCRIBE TO OUR NEWSLETTER</p>\r\n");
      out.write("                                <p class=\"text-secondary lh-1\">Get the latest updates on new products and upcoming\r\n");
      out.write("                                    sales</p>\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-12 col-md-6 offset-md-3\">\r\n");
      out.write("                                        <div class=\"input-group mb-3\">\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control\"\r\n");
      out.write("                                                   placeholder=\"Enter You Email Address\"\r\n");
      out.write("                                                   aria-describedby=\"button-addon2\">\r\n");
      out.write("                                            <button class=\"btn btn-outline-secondary\" type=\"button\" id=\"button-addon2\">\r\n");
      out.write("                                                Submit\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-12 col-md-3 text-center text-md-start mb-3 mb-md-0\">\r\n");
      out.write("                                <div class=\"row justify-content-center justify-content-md-start\">\r\n");
      out.write("                                    <div class=\"col-12 py-2 ms-md-0 text-center mb-3\">\r\n");
      out.write("                                        <img src=\"assets/images/logo/ezgif.com-gif-maker (1).gif\" class=\"img-fluid\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12 mb-3\">\r\n");
      out.write("                                        <p style=\"text-align: justify;\">\r\n");
      out.write("                                            Here we are the newTech.lk&trade; to support you for accomplish your\r\n");
      out.write("                                            desire by selling high quality products.\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12 ps-md-5 d-block d-md-none\">\r\n");
      out.write("                                        <p>Follow us on Social Media</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12 ps-md-0\">\r\n");
      out.write("                                        <ul class=\"list-unstyled  d-flex justify-content-md-evenly justify-content-center\">\r\n");
      out.write("                                            <li class=\"mx-lg-0 mx-1\">\r\n");
      out.write("                                                <a href=\"#\" class=\"form-floating btn-sm text-primary card text-nuro\"\r\n");
      out.write("                                                   style=\"font-size: 19px;\">\r\n");
      out.write("                                                    <i class=\"bi bi-facebook px-1\"></i>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"mx-lg-0 mx-1\">\r\n");
      out.write("                                                <a href=\"#\" class=\"form-floating btn-sm text-danger card text-nuro\"\r\n");
      out.write("                                                   style=\"font-size: 19px;\">\r\n");
      out.write("                                                    <i class=\"bi bi-youtube px-1\"></i>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"mx-lg-0 mx-1\">\r\n");
      out.write("                                                <a href=\"#\" class=\"form-floating btn-sm text-info card text-nuro\"\r\n");
      out.write("                                                   style=\"font-size: 19px;\">\r\n");
      out.write("                                                    <i class=\"bi bi-twitter px-1\"></i>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"mx-lg-0 mx-1\">\r\n");
      out.write("                                                <a href=\"#\" class=\"form-floating btn-sm text-danger card text-nuro\"\r\n");
      out.write("                                                   style=\"font-size: 19px;\">\r\n");
      out.write("                                                    <i class=\"bi bi-google px-1\"></i>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"mx-lg-0 mx-1\">\r\n");
      out.write("                                                <a href=\"#\" class=\"form-floating btn-sm text-primary-50 card text-nuro\"\r\n");
      out.write("                                                   style=\"font-size: 19px;\">\r\n");
      out.write("                                                    <i class=\"bi bi-linkedin px-1\"></i>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-12 col-md-3 d-none d-md-block\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-12 ps-5 mb-3 border border-3 border-bottom-0 border-end-0 border-top-0 border-primary\">\r\n");
      out.write("                                        <span class=\"fw-bold\">Site Map</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12 text-white-50 ps-3  lh-lg\">\r\n");
      out.write("                                        <ul style=\"list-style: none;\">\r\n");
      out.write("                                            <li><a class=\"footerlink\" href=\"index\">Home</a></li>\r\n");
      out.write("                                            <li><a class=\"footerlink\" href=\"wishlist\">Wishlist</a></li>\r\n");
      out.write("                                            <li><a class=\"footerlink\" href=\"cart\">Cart</a></li>\r\n");
      out.write("                                            <li><a class=\"footerlink\" href=\"invoice\">Invoice</a></li>\r\n");
      out.write("                                            <li><a class=\"footerlink\" href=\"purchasehistory\">Purchase\r\n");
      out.write("                                                History</a></li>\r\n");
      out.write("                                            <li><a class=\"footerlink\" href=\"advancedsearch\">Advanced Search</a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-12 col-md-3 d-none d-md-block\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-12 ps-5 mb-3 border border-3 border-bottom-0 border-end-0 border-top-0 border-primary\">\r\n");
      out.write("                                        <span class=\"fw-bold\">Shop</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12 text-white-50 ps-3 lh-lg\">\r\n");
      out.write("                                        <ul style=\"list-style: none;\">\r\n");
      out.write("                                            <li><a class=\"footerlink\" href=\"index\">Electronics</a></li>\r\n");
      out.write("                                            <li><a class=\"footerlink\" href=\"wishlist\">Computers & Laptops</a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li><a class=\"footerlink\" href=\"cart\">Drones</a></li>\r\n");
      out.write("                                            <li><a class=\"footerlink\" href=\"invoice\">Earphones</a></li>\r\n");
      out.write("                                            <li><a class=\"footerlink\" href=\"purchasehistory\">Smart Phones</a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li><a class=\"footerlink\" href=\"advancedSearch\">Cameras</a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-12 col-md-3 text-center text-md-start\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-12 ps-4 mb-3 border border-3 border-bottom-0 border-end-0 border-top-0 border-primary d-none d-md-block\">\r\n");
      out.write("                                        <span class=\"fw-bold\">Contact</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12 mb-3 d-block d-md-none\">\r\n");
      out.write("                                        <span class=\"fw-bold\">Contact</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12 ps-0 ps-md-4  lh-lg\" style=\"color: rgb(81, 150, 196);\">\r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            <i class=\"bi bi-house-fill pe-1\"></i>Udahamullah, Nugegoda, Sri Lanka\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            <i class=\"bi bi-envelope-fill pe-1\"></i>newTech@gmail.com\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            <i class=\"bi bi-telephone-fill pe-1\"></i>+94243546724\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            <i class=\"bi bi-printer-fill pe-1\"></i>+94243546724\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <div class=\"d-flex justify-content-center mb-5 px-3\">\r\n");
      out.write("                            <img src=\"assets/images/otherAppImages/trust_551fa8e0-5f24-4fbc-bf22-74c01b859a01.webp\"\r\n");
      out.write("                                 alt=\"\" class=\"img-fluid\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <div class=\"col-12 text-center\">\r\n");
      out.write("                            <span>\r\n");
      out.write("                                Copyright &copy;2021 newTech All Rights Reserved.\r\n");
      out.write("                            </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </footer>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Footter End -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Cookie Accept Start -->\r\n");
      out.write("        <!-- <div class=\"position-fixed bottom-0 start-0 p-3\" style=\"z-index: 11\">\r\n");
      out.write("            <div class=\"toast show bg-dark text-white\" role=\"alert\" aria-live=\"assertive\" aria-atomic=\"false\" id=\"toast\">\r\n");
      out.write("                <div class=\"toast-header bg-dark text-white\">\r\n");
      out.write("                    <strong class=\"me-auto fs-5\">Allow Cookies</strong>\r\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"toast\" style=\"color: whitesmoke !important; background-color: white;\" onclick=\"closeToast();\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"toast-body d-grid\">\r\n");
      out.write("                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet, magnam!</p>\r\n");
      out.write("                    <button class=\"btn btn-success btn-sm rounded-3\" onclick=\"closeToast();\">Allow Cookies</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> -->\r\n");
      out.write("        <!-- Cookie Accept End -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Scrolltop button -->\r\n");
      out.write("        <button class=\"scroll-top-btn\" onclick=\"toTop()\" id=\"scrollTopBtn\">\r\n");
      out.write("            <i class=\"bi bi-caret-up-fill\"></i>\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- scripts for timer -->\r\n");
      if (_jspx_meth_layout_005fblock_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fblock_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:block
    lk.callidora.jsp.inheritance.BlockTag _jspx_th_layout_005fblock_005f0 = new lk.callidora.jsp.inheritance.BlockTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fblock_005f0);
    try {
      _jspx_th_layout_005fblock_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/layout/base.jsp(14,4) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fblock_005f0.setName("baseCss");
      _jspx_th_layout_005fblock_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fblock_005f0, null));
      _jspx_th_layout_005fblock_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fblock_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fblock_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  layout:block
    lk.callidora.jsp.inheritance.BlockTag _jspx_th_layout_005fblock_005f1 = new lk.callidora.jsp.inheritance.BlockTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fblock_005f1);
    try {
      _jspx_th_layout_005fblock_005f1.setJspContext(_jspx_page_context);
      // /WEB-INF/views/layout/base.jsp(285,8) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fblock_005f1.setName("contents");
      _jspx_th_layout_005fblock_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fblock_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fblock_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:block
    lk.callidora.jsp.inheritance.BlockTag _jspx_th_layout_005fblock_005f2 = new lk.callidora.jsp.inheritance.BlockTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fblock_005f2);
    try {
      _jspx_th_layout_005fblock_005f2.setJspContext(_jspx_page_context);
      // /WEB-INF/views/layout/base.jsp(467,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fblock_005f2.setName("baseStyle");
      _jspx_th_layout_005fblock_005f2.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fblock_005f2, null));
      _jspx_th_layout_005fblock_005f2.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fblock_005f2);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\"\r\n");
      out.write("              integrity=\"sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==\"\r\n");
      out.write("              crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"/>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css\"/>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/frameworks/css/bootstrap.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/frameworks/css/style.css\">\r\n");
      out.write("    ");
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"\r\n");
      out.write("            integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"assets/frameworks/js/jquery.countdown.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        //Deal-Space-Timer\r\n");
      out.write("        $('[data-countdown]').each(function () {\r\n");
      out.write("            var $this = $(this),\r\n");
      out.write("                finalDate = $(this).data('countdown');\r\n");
      out.write("            $this.countdown(finalDate, function (event) {\r\n");
      out.write("                $this.html(event.strftime('<div class=\"col-3 me-0 px-0 deal-timer\">' + '%D' + '<br></div>' +\r\n");
      out.write("                    '<div class=\"col-3 mx-0 px-0 deal-timer\">' + '%H' + '<br></div>' +\r\n");
      out.write("                    '<div class=\"col-3 mx-0 px-0 deal-timer\">' + '%M' + '<br></div>' +\r\n");
      out.write("                    '<div class=\"col-3 mx-0 px-0 deal-timer\">' + '%S' + '<br></div>'));\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"assets/frameworks/js/bootstrap.bundle.min.js \"></script>\r\n");
      out.write("    <script src=\"assets/frameworks/js/script.js \"></script>\r\n");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
